### ISSUE TITLE
Add a formatter for tree-sitter's query language

### ISSUE THREAD

**Issue by aspiwack** [tweag/topiary#101]
**Is your feature request related to a problem? Please describe.**
Our formatters' logic, are written in tree-sitter's query language, a [scheme-like language](https://github.com/tweag/topiary/pull/100#issuecomment-1305173729). These queries are currently not formatted by a code formatter.

**Describe the solution you'd like**
In the spirit of dog-fooding (and because I'm not actually aware of an existing formatter), I suggest that we make a formatter for the query language, and format our queries with it.

**Comment by figsoda** [comment]
There is also https://github.com/tree-sitter/tree-sitter-tsq and https://github.com/nvim-treesitter/tree-sitter-query

**Comment by Xophmeister** [comment]
It's perhaps worth mentioning that the way we're currently hand-formatting our queries is different from how S-expressions are (usually?[^1]) formatted. For example:

How we'd format the query (taken from the OCaml queries):
```scheme
(
  (value_definition) @append_hardline
  .
  [
    (exception_definition)
    (external)
    (module_definition)
    (module_type_definition)
    (open_module)
    (type_definition)
    (value_definition)
  ]
)
```

How it might look if it were considered a Lisp:
```scheme
((value_definition) @append_hardline
                    . [(exception_definition)
                       (external)
                       (module_definition)
                       (module_type_definition)
                       (open_module)
                       (type_definition)
                       (value_definition)])
```

(Note: It's typical to see sibling alignment in S-expressions; see #170.)

Of course, that's not to say we _have_ to format an S-expression language as though it were a Lisp! (Although there's a precedent: they are written this way in the [Tree Sitter documentation](https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries), for example.)

[^1]: I only have experience with Racket style, I assume other Schemes are the same; I can't speak to Common Lisp.

**Comment by nbacquey** [comment]
Now that we have successfully used a tree-sitter query grammar in #315 , I will add support for tree-sitter query formatting
