### ISSUE TITLE
Hard-tab support

### ISSUE THREAD

**Issue by Xophmeister** [tweag/topiary#105]
At the risk of starting a Holy War, `(#indent-level! 4)` implies soft-tabs; i.e., a number of spaces. _Some_ people prefer hard-tabs (i.e., a single `\t` at each indentation level) and some codebases -- misguided though they may be -- expect them per their style guide.

I propose updating the format of this directive such that its parameter is either:
* A digit, representing the number of spaces in a soft-tab (as now);
* Or a `t`, say, representing hard-tab indentation.

**Comment by aspiwack** [comment]
Why not.

It isn't something that is needed for the first release. But when that's done, it will be something to consider.

**Comment by haikyuu** [comment]
More than a preference, some languages actually require using tabs. i.e [imba](imba.io).
I'm actually working on its tree-sitter grammar and I want to use topiary at some point to format imba code.
