### ISSUE TITLE
Topiary reports a parsing error on a valid OCaml file

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#106]
## Bug Description

Topiary reports parsing errors on OCaml files manipulating [first-class modules](https://v2.ocaml.org/manual/firstclassmodules.html), even when they are valid OCaml files. The error does not seem to come from the OCaml tree-sitter grammar that parses such constructions just fine.

## Expected Behaviour

Considering that tree-sitter parses such constructions correctly, I would expect Topiary to succeed in parsing, potentially failing elsewhere. As a user, I would expect that running Topiary on my file either succeeds (even if it leads to an odd formatting) or reports an error that does not have to do with parsing. For instance, something about an unsupported construct in the query file?

## Environment

- NixOS unstable with [nixpkgs](https://github.com/NixOS/nixpkgs/) at commit [`6060f12`](https://github.com/NixOS/nixpkgs/commit/6060f1268ca7b44d62304564eadb0b0667ea8b84).
- OCaml and tree-sitter from aforementioned [nixpkgs](https://github.com/NixOS/nixpkgs/).
- Topiary on `main` as of December 1st, 2022, at commit 534b3d0.
- [tree-sitter-ocaml](https://github.com/tree-sitter/tree-sitter-ocaml) at commit [`cc26b1e`](https://github.com/tree-sitter/tree-sitter-ocaml/commit/cc26b1ef111100f26a137bcbcd39fd4e35be9a59).

## Reproduction

My protocol is to create a file using first-class modules and to run OCaml, Topiary and tree-sitter on it, to show that both OCaml and tree-sitter agree that the file is syntactically correct while Topiary reports a syntax error. Each invocation of `nix run github:nixos/nixpkgs/6060f12#<command> --` (or `nix run <flake>#<command> --` in general) can be replaced by a direct invocation of `<command>` if you have it on your machine.

1. Create an ML file named `issue106.ml` with the following content:
   ```ocaml
   module type FOO = sig val foo : string end
   let create foo : (module FOO) = (module struct let foo = foo end)
   module Foo = (val create "Issue #106")
   ```

2. Confirm that it is a valid OCaml file by running OCaml on it and not getting an error:
   ```console
   $ nix run github:nixos/nixpkgs/6060f12#ocaml -- issue106.ml
   ```

2. Run Topiary as of commit 534b3d0 on it. For instance, I would run:
   ```console
   $ commit=534b3d0
   $ wget https://raw.githubusercontent.com/tweag/topiary/$commit/languages/ocaml.scm --output-document=ocaml.scm
   $ nix run github:tweag/topiary/$commit -- --query ocaml.scm --input-file issue106.ml
   ```

4. Confirm that you get a parsing error, eg.:
   ```console
   Error: Parsing error between line 1, column 19 and line 1, column 30
   ```

5. Note that, as of 534b3d0, Topiary relies on [tree-sitter/tree-sitter-ocaml](https://github.com/tree-sitter/tree-sitter-ocaml) as of commit [`cc26b1e`](https://github.com/tree-sitter/tree-sitter-ocaml/commit/cc26b1ef111100f26a137bcbcd39fd4e35be9a59):
   https://github.com/tweag/topiary/blob/534b3d0ada72388e1fee50092c8fe83fc9dc649c/Cargo.lock#L687

6. Setup tree-sitter with this version of OCaml's grammar. For instance, I did the following:
   1. Create an initial configuration for tree-sitter:
      ```console
      $ nix run github:nixos/nixpkgs/6060f12#tree-sitter -- init-config
      Saved initial configuration to ~/.config/tree-sitter/config.json
      ```
   2. Check which directories tree-sitter uses for languages:
      ```console
      $ cat ~/.config/tree-sitter/config.json
      {
        "parser-directories": [
          "~/github",
          "~/src",
          "~/source"
        ],
        "theme": {
            ...
      ```
   3. Create one of those directories, get in it and get the OCaml grammar:
      ```console
      $ mkdir ~/source
      $ cd ~/source
      $ wget -qO- https://github.com/tree-sitter/tree-sitter-ocaml/archive/cc26b1e.tar.gz | tar xz
      ```
   4. Check that tree-sitter sees the grammar in question:
      ```console
      $ nix run github:nixos/nixpkgs/6060f12#tree-sitter -- dump-languages
      scope: source.ocaml
      parser: "~/source/tree-sitter-ocaml-cc26b1ef111100f26a137bcbcd39fd4e35be9a59/ocaml"
      highlights: None
      file_types: ["ml"]
      content_regex: None
      injection_regex: Some(^(ocaml|ml)$)
      
      scope: source.ocaml.interface
      parser: "~/source/tree-sitter-ocaml-cc26b1ef111100f26a137bcbcd39fd4e35be9a59/interface"
      highlights: None
      file_types: ["mli"]
      content_regex: None
      injection_regex: Some(^ocaml_interface$)
      ```

7. Run tree-sitter with this version of OCaml's grammar on the previous file:
   ```console
   $ nix run github:nixos/nixpkgs/6060f12#tree-sitter -- parse issue106.ml
   (compilation_unit [0, 0] - [3, 0]
     (module_type_definition [0, 0] - [0, 42]
       name: (module_type_name [0, 12] - [0, 15])
       ...
   ```
   In particular, note that the return code is `0` and that there is no error printed at the end of parsing.

8. Optionally, add an obvious OCaml error to `issue106.ml` and check that both OCaml (step 2.) and tree-sitter (step 7.) find it. For instance:
   ```console
   $ echo BONJOUR >> issue106.ml
   $ nix run github:nixos/nixpkgs/6060f12#ocaml -- issue106.ml
   File "./issue106.ml", line 4, characters 0-7:
   4 | BONJOUR
       ^^^^^^^
   Error: Syntax error
   $ nix run github:nixos/nixpkgs/6060f12#tree-sitter -- parse issue106.ml
   (compilation_unit [0, 0] - [3, 0]
     (module_type_definition [0, 0] - [0, 42]
       name: (module_type_name [0, 12] - [0, 15])
       ...
     (ERROR [3, 0] - [3, 7]))
   issue106.ml	0 ms	(ERROR [3, 0] - [3, 7])
   ```

**Comment by Niols** [comment]
@GuillaumeGen suggested that I add a test case corresponding to this example file to see if we could reproduce the bug above. This is done in branch `niols/issue106` at commit b78d9fe. Funnily enough, on this branch, `cargo test` does not exhibit the same behaviour as above, but rather:

```
failures:

---- input_output_tester stdout ----
thread 'input_output_tester' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<module type FOO = sig val foo : string end
<let create foo : (module FOO) = (module struct let foo = foo end)
<module Foo = (val create "Issue #106")
>module type FOO = sigvalfoo : string
<
```

Apart from the fact that the diff looks a bit broken, it shows that there is no parse error! There might be a difference in the way Topiary calls the OCaml tree-sitter grammar during tests and with `nix run ...`.

**Comment by Niols** [comment]
Good catch!
```console
$ nix run github:tweag/topiary/$commit -- --query ocaml.scm --input-file issue106.ml --skip-idempotence
module type FOO = sigvalfoo : string
```
I guess this becomes more an issue of error reporting in Topiary. In that case, I think it should report a problem of idempotence (potentially a very severe one if the first pass yield unparseable results) and not a parse error.

**Comment by GuillaumeGen** [comment]
Yes, the first pass of Topiary leads to an invalid Ocaml program.
The reason for this is that `end` is a keyword triggering an "end of indentation". Since neither `val` nor `sig` opened an indentation, the line `module type FOO = sig val foo : string end` lead to an "end of indentation" right before the `end` and made Topiary stop. The program after it is then invalid, both because `sigval` is not a keyword and because the `end` is missing. That's precisely the problems #110 solve.

**Comment by torhovland** [comment]
Ideally, the error reporting should be improved here as well, like @Niols suggests. So if the second run causes a parse error, but not the first, then it isn't really a parse error, but a formatting error.
