### ISSUE TITLE
Infer language from the file name of the query instead of a query directive

### ISSUE THREAD

**Issue by figsoda** [tweag/topiary#108]
Currently, the query file is being parsed twice since we need to find the `language` directive before being able to use [Query::new](https://docs.rs/tree-sitter/latest/tree_sitter/struct.Query.html#method.new)

If the language is inferred from the file name (or overridden with `--language`), this could be avoided by using [Query::general_predicaes](https://docs.rs/tree-sitter/latest/tree_sitter/struct.Query.html#method.general_predicates) to parse the indent directives, it will also make it easier to add more directives in the future

**Comment by torhovland** [comment]
Keep in mind that when you say "parsed twice" it doesn't mean parsed with tree-sitter twice, it just means that there is an additional scan for configuration predicates.

The way it works now makes it easy to have variants of the query file that won't have the exact same name as the language.
