### ISSUE TITLE
Command line option for outputting the tree-sitter syntax tree

### ISSUE THREAD

**Issue by torhovland** [tweag/topiary#11]
Helpful when developing queries.

---

Implementation plan:
* [x] Refactor/structure source, so binary-related functions can be kept distinct from the library.
* [x] ~Implement/expose Tree-sitter syntax tree output in the library.~ Shore up `Language` machinery for Tree-sitter's sake.
* [x] Implement JSON serialisation of syntax output in the binary.
* [x] Expose feature through CLI flag (+ document)
* [ ] Stretch: Implement DOT serialisation of syntax output in the binary

**Comment by Xophmeister** [comment]
I'm going to take this, now the v0.1 issues are done, to improve my Rust :ok_hand:
