### ISSUE TITLE
Multiline comments in Ocaml are badly indented

### ISSUE THREAD

**Issue by GuillaumeGen** [tweag/topiary#111]
When an Ocaml file contains multiline comments, those are badly displayed because the first line is the only indented one.

So 
```ocaml
  (* The identity function does not have the declared type at all,
      it is just for formatting verification purpose.
  *)
  fun x -> x
```

can be turned into

```ocaml
    (* The identity function does not have the declared type at all,
      it is just for formatting verification purpose.
  *)
    fun x -> x
```

The reason for it, is that topiary evaluated that the function body should be indented by 2 levels whereas I indented it by only one, hence it indented the beginning of the comment with the function body, but since the whole comment is a leaf, the other lines kept the number of spaces I originally put in it.

**Describe the solution you'd like**
Ideally, I would love the text in the comment to be indented consistently.

If not, possible, turning multiline comments into single line ones, for which this problem does not occur, could be a workaround.

If both are not possible (and modifying a leaf is not the purpose of tree-sitter queries, so both are probably not possible), then keeping the indentation the user gave to comments would probably be less ugly than the current result.

**Comment by aspiwack** [comment]
This sounds like something that the engine should be doing transparently.

**Comment by nbacquey** [comment]
Here is a minimal reproducer:
```ocaml
let _ = fun _ ->
  (* foo
  *)
  ()
```
gets formatted as:
```ocaml
let _ = fun _ ->
    (* foo
  *)
    ()
```

**Comment by torhovland** [comment]
A few possible approaches:

- Use a new predicate to mark certain nodes as indented leaves. Whenever processing indenting, check if the block contains indented leaves. If so, indent each line.
- Use a new predicate to mark certain nodes as indented leaves. When processing the predicate, add each line as a leaf. Indenting will then work as intended (no pun intended (not this one either)).

**Comment by torhovland** [comment]
Idempotency is complicating things a bit. We don't want to indent twice. So I am taking all lines that may or may not begin with the correct indent level of spacing, and replacing that with the correct indent level of spacing. Which means that this:

```
(* A multi-line comment
that explains
  - something
  - and something else
*)
```

will all get indented as such:

```
  (* A multi-line comment
  that explains
  - something
  - and something else
  *)
```

**Comment by torhovland** [comment]
Another example:

```rust
enum ExpandTwoLevels {
    Leaf {
    /*
     * Multi-line
     * comment
     */
        content: String,
    },
}
```

Consider lines 2-4 of that comment. They all begin with 5 spaces. How do we treat them? We know they are not put there as indentation by Topiary, because that would have ben 8 spaces. So they are one of these:

- wrong indentation put there by the author (should ideally be discarded)
- meaningful spacing put there by the author (should ideally be kept)

We don't know which it is, so the best we can do is to keep it. Which means that after indentation they get 8 + 5 spaces:

```rust
enum ExpandTwoLevels {
    Leaf {
        /*
             * Multi-line
             * comment
             */
        content: String,
    },
}
```

**Comment by torhovland** [comment]
Should I instead decide that since the comment starts on column 4, I should clean out up to 4 spaces from the beginning of all following lines, before indenting?

**Comment by GuillaumeGen** [comment]
Yes, I think that this is the best solution, if the comments starts after `n` spaces, then all the comment lines starting with `m>=n` spaces should start by `m-n+indentation_level` spaces, and lines starting with less than `n`spaces could probably be kept as is (probably, to be discussed).
Would remain the question of code likes:
```
let f = /* Here I start to comment,
         * But not after spaces.
         * How to deal with it?
         */
    1
```

**Comment by torhovland** [comment]
Hi, @GuillaumeGen 🙂

Looks like what we really need is to compare which column the comment originally starts on (`a`) with the column we put it on after formatting (`b`). Then we know the indent level (`b-a`), and can add the same indenting to the remaining lines if positive, or remove up to `a-b` spaces from the beginning of each line if not.

But we don't know `b` until pretty-printing, so this will all have to happen there.
