### ISSUE TITLE
Topiary cannot open files when invoked outside of its repository

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#121]
**Describe the bug**
I tried to run topiary on the [tezos](https://gitlab.com/tezos/tezos) codebase, and realized that when I tried to invoke `topiary` outside of its repository directory, it would fail with
```
Error: Writing error
  Caused by: No such file or directory (os error 2)
```

**To Reproduce**
At the root of `topiary`'s repository, run the following:
```
nicolas@elwood:~/tweag/topiary$ touch ../testfile.ml
nicolas@elwood:~/tweag/topiary$ topiary --input-file ../testfile.ml 

nicolas@elwood:~/tweag/topiary$ cd ..
nicolas@elwood:~/tweag$ topiary --input-file testfile.ml 
Error: Writing error
  Caused by: No such file or directory (os error 2)
```

**Expected behavior**
I would expect `topiary`'s invocation to work regardless of the working directory

**Environment**
 - Ubuntu 22.04.1 LTS
 - `main` on 2022-12-13 (https://github.com/tweag/topiary/commit/b0267bb3aefdb95fda75a057ca3d4eb73f79c3ac)

**Additional context**
- Rust debug log gives no additional information:
```
nicolas@elwood:~/tweag$ RUST_LOG=debug topiary --input-file ../testfile.ml 
Error: Writing error
  Caused by: No such file or directory (os error 2)
```
- Renaming the test file from `testfile.ml` to `testfile` yields an expected behaviour:
```
nicolas@elwood:~/tweag$ RUST_LOG=debug topiary --input-file testfile
Error: Cannot detect language of file 'testfile'. Try specifying language explicitly.
```
- The problem persists with non-empty input files

**Comment by GuillaumeGen** [comment]
A little investigation tells me that the issue is that the path to the query file is `languages/ocaml.scm` even outside of the topiary folder. Adding a print of the query path in line 90 of `main.rs`:
```
    print!("Query path is {query_path:?}\n");
    let mut query = BufReader::new(File::open(query_path)?);
 ```
 always displays `"languages/ocaml.scm`
 Remains the question of why this is a writing error and not a reading one.

**Comment by Xophmeister** [comment]
The query path is hardcoded to be `languages/<language>.scm`. Rust must interpret this to mean "relative to the CWD", rather than "relative to the binary's directory" -- which makes sense, tbh.

This is not a fix, but a workaround is to set the `TOPIARY_LANGUAGE_DIR` environment variable.

**Comment by torhovland** [comment]
> Remains the question of why this is a writing error and not a reading one.

I suppose this one is too cheeky:

```rust
impl From<io::Error> for FormatterError {
    fn from(e: io::Error) -> Self {
        FormatterError::Writing(WritingError::Io(e))
    }
}
```

**Comment by aspiwack** [comment]
For the record, this was the subject of #107 .

Now, there is a bit of discussion to have on what we would like the solution to be like.

Maybe the answer is auto-detected languages or `--language` map to the installed directory, whereas `--query-file` (I'm not sure I'm remembering this option's name right) reads in `pwd` by default?

**Comment by nbacquey** [comment]
> This is not a fix, but a workaround to unblock you is to set the TOPIARY_LANGUAGE_DIR environment variable.

The workaround works, but it took me a little while to figure out that the variable had to be set at _compile_ time, not at _runtime_. Thanks!
