### ISSUE TITLE
[Ocaml] Multiline let-ins are turned into single one

### ISSUE THREAD

**Issue by GuillaumeGen** [tweag/topiary#133]
When one writes 
```
let f x = a in
some_expression
```
topiary currently turns it into
```
let f x = a in some_expression
```

This is not the expected behaviour, as it turns the expression node from a multiline node to a single line one.

**Additional context**
The reason for this is that currently we do allow line breaks after the "in" keyword only for some very specific constructs https://github.com/tweag/topiary/blob/d7f746dd24b15ec47506f9df3a811646d31f148f/languages/ocaml.scm#L437-L453 . This is way too restrictive.

**Comment by aspiwack** [comment]
Mmm… do we remember why we don't systematically append a (spaced) softline after `in`. Regardless of what comes after?

**Comment by torhovland** [comment]
If we do, it means we want to have:

```ocaml
      let edges =
        ...
      in
      node::List.fold_left (explore (node::path))
```

rather than:

```ocaml
      let edges =
        ...
      in node::List.fold_left (explore (node::path))
```

What do you think?

**Comment by GuillaumeGen** [comment]
I clearly prefer the former, if only because I do not want to have things indented by 3 characters in the next line.

**Comment by torhovland** [comment]
> do we remember why we don't systematically append a (spaced) softline after in

So that's basically what #134 does. It seems OK as long as the example above looks fine.

But there's no indentation added. How will this look if there's a multi-line block following `in`?
