### ISSUE TITLE
Bash formatting support

### ISSUE THREAD

**Issue by Xophmeister** [tweag/topiary#138]
**Is your feature request related to a problem? Please describe.**
AFAIK, there is no de facto Bash/shell script formatter. It is _very_ common to come across horrendously formatted shell scripts!

**Describe the solution you'd like**
Bash support in Topiary. (Bash, for now; perhaps POSIX `sh`, `zsh`, etc. in the future.)

**Describe alternatives you've considered**
n/a

**Additional context**
Having Bash support, alongside OCaml, JSON and TOML, in the first -- or an early -- release would be a good demonstration of both the general-ness of the engine and the potential for the project.

(Grammar: https://github.com/tree-sitter/tree-sitter-bash)

---

* [x] Update Rust code
* [x] Commands, command lists and command pipelines
* [x] Conditionals
* [x] Switch statements
* [x] Loops
* [x] Redirection and heredocs
* [x] Compound statements
* [x] Variables (declaration and expansion)
* [x] Command and process substitution
* [x] Subshells
* [x] Functions
* [x] (Opinionated) line spacing
* [x] Comments

**Comment by Niols** [comment]
I'm not sure what you mean by “de facto” Bash formatters, but there do exist some Shell formatters, including for instance [shfmt](https://github.com/mvdan/sh). Don't get me wrong, I'm super excited to see it included in Topiary, I just wouldn't want someone somewhere to claim there were no other Shell formatters!

**Comment by Xophmeister** [comment]
> I'm not sure what you mean by “de facto” Bash formatters, but there do exist some Shell formatters, including for instance [shfmt](https://github.com/mvdan/sh).

Good point. What I mean is that -- in my experience, at least -- it's not common for formatters to be applied to Bash scripts and no particular formatter has a significant mindshare, not that they don't exist. (Compared with, e.g., linters, where many would immediately jump to Shellcheck.)

**Comment by Niols** [comment]
That makes sense and I completely agree. Hopefully, that is something Topiary could bring to the table: if it's already a dependency of your project, why not make it format your Shell files as well?

**Comment by Xophmeister** [comment]
n.b., Line spacing is a bit messed up, but it's "good enough"; see #203.
