### ISSUE TITLE
[OCaml] constructors in left-hand side of assignments are not spaced correctly

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#139]
**Describe the bug**
When running topiary on the following:
```
let Some foo = Some bar
```
The output is
```
let Somefoo = Some bar
```

**To Reproduce**
* Run `echo "let Some foo = Some bar" | topiary -s -q languages/ocaml.scm -i /dev/stdin`
* Observe that the output is the one described

**Expected behavior**
The output should be the same as the input.

**Environment**
 Ubuntu 22.04 + `main` as of 2022-12-19 (https://github.com/tweag/topiary/commit/ac40fb1d182627a0992f5886b1c6d032fc9a5c52)

**Comment by torhovland** [comment]
It looks like the idempotency check is tricking you here:

```
{Node constructor_name (0, 4) - (0, 11)} - Named: true
```

This is likely because the first pass is outputting `Somefoo`, and then the second pass thinks that is one atom.

Try running without idempotency check.

**Comment by nbacquey** [comment]
Unless I'm mistaken, the `-s` option in the command line disables the idempotency check, doesn't it?

**Comment by torhovland** [comment]
Yes, it does. Hmm, in that case it looks odd.

**Comment by nbacquey** [comment]
My bad you are right: I was too eager in reading the log lines: the first tree is correct
```
{Node compilation_unit (0, 0) - (1, 0)} - Named: true
  {Node value_definition (0, 0) - (0, 23)} - Named: true
    {Node let (0, 0) - (0, 3)} - Named: false
    {Node let_binding (0, 4) - (0, 23)} - Named: true
      {Node constructor_pattern (0, 4) - (0, 12)} - Named: true
        {Node constructor_path (0, 4) - (0, 8)} - Named: true
          {Node constructor_name (0, 4) - (0, 8)} - Named: true
        {Node value_name (0, 9) - (0, 12)} - Named: true
      {Node = (0, 13) - (0, 14)} - Named: false
      {Node application_expression (0, 15) - (0, 23)} - Named: true
        {Node constructor_path (0, 15) - (0, 19)} - Named: true
          {Node constructor_name (0, 15) - (0, 19)} - Named: true
        {Node value_path (0, 20) - (0, 23)} - Named: true
          {Node value_name (0, 20) - (0, 23)} - Named: true
```

**Comment by nbacquey** [comment]
Edited the issue to reflect this new analysis. I will solve it shortly
