### ISSUE TITLE
[Rust] tree-sitter-rust 0.20.3 does not recognise the if_let_expression node type

### ISSUE THREAD

**Issue by Xophmeister** [tweag/topiary#147]
**Describe the bug**
The tree-sitter-rust crate no longer supports the `if_let_expression` node type, as of v0.20.3. As such, the Rust language query file cannot be parsed.

**To Reproduce**
* `cargo update -p tree-sitter-rust --precise 0.20.3`
* `cargo test`

**Expected behavior**
The tests should pass without a query parsing error.

**Environment**
 - OS name + version: NixOS 22.05
 - Version of the code: 6c5b58c7d1b6

**Additional context**
Pinning to 0.20.2 resolves the problem. I suspect the name of the node type has simply changed, but this needs investigation...

**Comment by Xophmeister** [comment]
Looks like the change was made here: https://github.com/tree-sitter/tree-sitter-rust/commit/6ebdb1dc6cf4c19d8bae1d04f7bad44408e877d8

**Comment by torhovland** [comment]
That sounds like a good change, as `if` and `let` are already handled. You may only have to remove this:

```scheme
(if_let_expression
  [
    (identifier)
    "let"
  ] @prepend_space
)
```

**Comment by torhovland** [comment]
One could question their (mis)use of semantic versioning, though 🙂
