### ISSUE TITLE
[OCaml] some parts of negative numbers aren't parsed correctly

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#153]
**Describe the bug**
When used in pattern matching, the numeral part of negative numbers isn't output.
Consider the following code:
```
function -1 -> -1
```
Its parsing tree is the following:
```
{Node compilation_unit (0, 0) - (1, 0)} - Named: true
  {Node expression_item (0, 0) - (0, 17)} - Named: true
    {Node function_expression (0, 0) - (0, 17)} - Named: true
      {Node function (0, 0) - (0, 8)} - Named: false
      {Node match_case (0, 9) - (0, 17)} - Named: true
        {Node signed_number (0, 9) - (0, 11)} - Named: true
          {Node - (0, 9) - (0, 10)} - Named: false
        {Node -> (0, 12) - (0, 14)} - Named: false
        {Node sign_expression (0, 15) - (0, 17)} - Named: true
          {Node sign_operator (0, 15) - (0, 16)} - Named: true
            {Node - (0, 15) - (0, 16)} - Named: false
          {Node number (0, 16) - (0, 17)} - Named: true
```
The nodes associated to the `-1` on the left of the arrow are:
```
{Node signed_number (0, 9) - (0, 11)} - Named: true
  {Node - (0, 9) - (0, 10)} - Named: false
```
There is no leaf node matching the `1`, hence the output of running topiary on the code above:
```
function - -> -1
```
The fix for this bug is quite simple (and presented in #152), though I wonder if we should report it in [tree-sitter-ocaml](https://github.com/tree-sitter/tree-sitter-ocaml).

**To Reproduce**
* run `$ echo "function -1 -> -1" | topiary -s --input-file /dev/stdin --query languages/ocaml.scm`
* witness that the output is `function - -> -1`

**Expected behavior**
The output of the command above should be `function -1 -> -1`

**Environment**
Ubuntu 22.04 + main on 2022-12-22 (https://github.com/tweag/topiary/commit/f364f2bbc56dd2e14d69e56d3aaca07a1344cc63)

**Comment by torhovland** [comment]
Looks like something you should report, yes.
