### ISSUE TITLE
[OCaml] Cubic time complexity when processing pattern matching with large number of cases

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#162]
**Describe the bug**
Topiary takes an unreasonable time to process the following function:
```
let big_match = function
  | 0 -> 0
  ...
  [repeat n times]
  ...
  | 0 -> 0
```
I've run topiary on a few files named `ocaml_n.ml`, which contain `n` repetitions of the pattern `| 0 -> 0`, as well as a real-life, 1200 lines long OCaml file containing a large pattern matching.
```
$ time ( topiary -s -i ocaml_real.ml > /dev/null 2>&1 )
real    0m17,029s
user    0m17,000s
sys     0m0,028s

$ time ( topiary -s -i ocaml_512.ml > /dev/null 2>&1 )
real    0m6,669s
user    0m6,661s
sys     0m0,008s

$ time ( topiary -s -i ocaml_1024.ml > /dev/null 2>&1 )
real    0m56,513s
user    0m56,489s
sys     0m0,021s

$ time ( topiary -s -i ocaml_2048.ml > /dev/null 2>&1 )
real    8m2,791s
user    8m2,752s
sys     0m0,009s
```
The results suggest there is an cubic behavior somewhere: doubling the number of cases multiplies the time by 8. Moreover, activating `RUST_LOG=debug` on `ocaml_2048.ml` produced a 540MB log file, containing over 2M lines.

**To Reproduce**
- retrieve the `ocaml_n.ml` files from [my branch](https://github.com/tweag/topiary/tree/nb/ocaml_time_experiments) , or produce them independently,
- run `time ( topiary -s -i ocaml_n.ml > /dev/null 2>&1 )`
- observe the unreasonable times

**Expected behavior**
We shouldn't take more than 0.1s to process a real-life, 1200 lines long OCaml file.

**Environment**
 - Ubuntu 22.04 + main on 2023-01-04 (https://github.com/tweag/topiary/commit/3a21fb5d982b77c75a7a4d4fdd859bccdac2fa34)

**Additional context**
I'm still trying to figure out if we have a query that produces an unreasonable number of nodes, a process that is unreasonably slow, or both.

**Comment by torhovland** [comment]
It would be nice to see the flamegraph. If you can't get that working (by installing `perf`), you can send me a sample file.

**Comment by nbacquey** [comment]
Here is the flamegraph for `ocaml_1024.ml`:
![flamegraph](https://user-images.githubusercontent.com/38809035/210540945-7ce66732-532f-4663-a3e0-0ab20e64d728.svg)
It seems we spend most of the time in `ts_query_cursor__compare_captures`

**Comment by torhovland** [comment]
You could run it without the idempotency check to make it easier to read, but unfortunately if something is cubic here, that seems to be tree-sitters query matching.

It's possible that we have one or more queries that could benefit from more `.` anchors to reduce the number of match permutations.

**Comment by torhovland** [comment]
Might also be interesting to study `ts_query_cursor__compare_captures` and see if there is room for improvement there.

**Comment by GuillaumeGen** [comment]
A simple huge win is to put an anchor between `"|"*` and `(match_case)` in line 626 of `ocaml.scm`.

**Comment by nbacquey** [comment]
@GuillaumeGen 's fix reduced the processing time of `ocaml_2048.ml` to `0.26s`, and the time of `ocaml_real.ml` to `0.60s`.
This is largely enough to close the issue.
