### ISSUE TITLE
[OCaml] Discussion about proper integration of `.mli` files

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#164]
There is almost nothing to do to make topiary able to process `.mli` (OCaml interface) files.

Almost nothing, but still something: [tree-sitter-ocaml](https://github.com/tree-sitter/tree-sitter-ocaml) has a separate grammar for `.mli` files, which we don't load at the moment. It is a small task to add support for `.mli` files as a completely separate language, which I have done in [this branch](https://github.com/tweag/topiary/tree/nb/ocaml_mli). I've called this "new" language `ocamli`.

However, there is a caveat: the query file we use for `.ml` files works perfectly fine for `.mli` files as well, except that the configuration line in the header must be `(#language! ocamli)` instead of `(#language! ocaml)` (to work properly with the `--query` cli option).

Currently in my branch, I've just copied `ocaml.scm` into `ocamli.scm`, and changed the header. I don't like this solution though, because it introduces a lot of code duplication. So far, I can see two alternatives:
1. make `ocamli.scm` a symlink to `ocaml.scm`.
2. introduce a bit of logic in the Rust code, don't make a separate `ocamli` language, allow to choose between the two parsers depending on whether the file is `.ml` or `.mli`, but always use the same query file.

Neither option are perfectly satisfactory, as they both forego the support of the `--query` option for `.mli` files, unless we introduce some logic of the form "if the first parser fails, try the second one".

What are your opinions on the matter?

**Environment**
- Ubuntu 22.04 + `main` on 2023-01-04 (https://github.com/tweag/topiary/commit/f6608f3e4308d67a4c7cdc32a216e353b4c40ada)

**Comment by GuillaumeGen** [comment]
`(#language! ...)` is a command we created for topiary, right?
Isn't it possible then to simply allow to have several of them in the same query file?

**Comment by nbacquey** [comment]
I suppose we can, but what would be the semantics?
If I understand correctly, the `(#language! ...)` statement pilots which grammar is used when topiary is invoked with the `--query FILE` option. If we allow several such statements, which grammar would we use? Each one in successive order until one succeeds? It seems a bit arbitrary, and possibly wasteful

**Comment by aspiwack** [comment]
Is it only a code-sharing question?

If so, are there code-sharing facilities in tree-sitter? Maybe the possibility to import/include a query file into another?

**Comment by torhovland** [comment]
It's not just a code-sharing question. It is also a question if the user is supposed to be aware that `.ml` and `.mli` are two distinct grammars, or if we should pretend that it's all just OCaml. I vote for the latter.

**Comment by aspiwack** [comment]
(As a side-note Ocaml doesn't mandate file extensions. You can mandate that a file be read as a `.ml` with the `-impl` option or as a `.mli` with the `-intf` option. I suppose we can pass query files explicitly for this case.)

What would be the rules when calling `--language ocaml`? If the file has a `.mli` extension, then use the `mli` query file, otherwise use the `.ml` query file? Ah but they both say they depend on the `ocaml` language.

As of now, “language” is how we select a tree-sitter grammar. You're proposing changing this. Fair enough, but do we need a name for tree-sitter grammars, if we need to specify one manually? But that would defeat your plan for code sharing, wouldn't it?

**Comment by torhovland** [comment]
This is what I think:

1. The code is deemed to be OCaml based on either file extension (`.ml` or `.mli`) or by `--language ocaml`. If none of these help us, exit with an error.
2. For each language we should maintain a prioritised list of grammars. Most languages will only have one grammar, but OCaml will have (1. `tree_sitter_ocaml::language_ocaml()` - 2. `tree_sitter_ocaml::language_ocaml_interface()`).
3. Parse the input until one grammar succeeds or all fail. *Question:* Can we imagine any scenario where this is wrong, i.e. `.mli` code successfully parses as `tree_sitter_ocaml::language_ocaml()` but is then not properly formatted?
4. Load the corresponding query file and format. For now it seems we only need one query file for each language, but it is possible we may later need one query file for each grammar. Let's assume for now we only need the former.

**Comment by aspiwack** [comment]
Aren't we worried about the computational cost of (3)?

**Comment by torhovland** [comment]
Not really. Parsing has a reasonable performance, and we're only talking about a slowdown of 2x for `.mli` files.

**Comment by aspiwack** [comment]
I'm worried that if we change our mind regarding this, we won't really have a way to pivot to a new strategy (well, we can assume that most people will only use automated detection anyway).

Ah. Maybe a solution would be: grammars have hierarchical names, like `ocaml.implementation` and `ocaml.interface`. Then `--language ocaml` means either, tried in a prescribed order. But I can `--language ocaml.interface` if I need.

**Comment by nbacquey** [comment]
> Question: Can we imagine any scenario where this is wrong, i.e. .mli code successfully parses as tree_sitter_ocaml::language_ocaml() but is then not properly formatted?

Regarding this: I've found some `.mli` files in the [tezos](https://gitlab.com/tezos/tezos) repository that parse correctly with the OCaml implementation grammar. Note that it does not answer the question: we would need to find files that parse correctly with the implementation grammar, _but_ produce a different tree than the one they would have produced with the interface grammar. I'm still searching for those.

**Comment by Xophmeister** [comment]
> Ah. Maybe a solution would be: grammars have hierarchical names, like `ocaml.implementation` and `ocaml.interface`. Then `--language ocaml` means either, tried in a prescribed order. But I can `--language ocaml.interface` if I need.

I like this idea; it seems relevant for, e.g., `shell(.posix)` vs. `shell.bash` vs. `shell.zsh`, etc. WRT the query files, maybe some kind of `import` declaration could be devised to avoid repeating yourself when you need to specify some kind of divergence.

**Comment by nbacquey** [comment]
I found several OCaml `.mli` files that parse correctly with both grammars, but produce a different tree depending on the grammar used.
Among the simplest examples, there is [this file](https://github.com/mirage/repr/blob/main/src/repr/type.mli) from the `repr` library:
```

(*
 * Copyright (c) 2016-2017 Thomas Gazagnaire <thomas@gazagnaire.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *)

(** Yet-another type combinator library
    [Repr] provides type combinators to define runtime representation for OCaml
    types and {{!generics} generic operations} to manipulate values with a
    runtime type representation.
    The type combinators supports all the usual {{!primitives} type primitives}
    but also compact definitions of {{!records} records} and {{!variants}
    variants}. It also allows the definition of run-time representations of
    {{!recursive} recursive types}. *)

include Type_intf.Type
(** @inline *)
```

When parsed with the interface grammar, we get (comments removed):
```
{Node compilation_unit (0, 0) - (29, 0)} - Named: true   
  {Node include_module_type (27, 0) - (27, 22)} - Named: true
    {Node include (27, 0) - (27, 7)} - Named: false
    {Node module_type_path (27, 8) - (27, 22)} - Named: true
      {Node extended_module_path (27, 8) - (27, 17)} - Named: true
        {Node module_name (27, 8) - (27, 17)} - Named: true
      {Node . (27, 17) - (27, 18)} - Named: false
      {Node module_type_name (27, 18) - (27, 22)} - Named: true
```
When parsed with the implementation grammar, we get (ditto):
```
{Node compilation_unit (0, 0) - (29, 0)} - Named: true   
  {Node include_module (27, 0) - (27, 22)} - Named: true
    {Node include (27, 0) - (27, 7)} - Named: false
    {Node module_path (27, 8) - (27, 22)} - Named: true
      {Node module_path (27, 8) - (27, 17)} - Named: true
        {Node module_name (27, 8) - (27, 17)} - Named: true
      {Node . (27, 17) - (27, 18)} - Named: false
      {Node module_name (27, 18) - (27, 22)} - Named: true
```
Note that there is a 1-to-1 mapping between nodes.
It seems that if we want to ensure that there is no formatting difference _for this particular file_, it is sufficient to ensure that the following equivalence classes are enforced in the query file:

- `include_module`, `include_module_type`
- `module_type_path`, `module_path`, `extended_module_path`

**Comment by torhovland** [comment]
OK, so thus far it does look like we _can_ use the same query file for both dialects without conflicts. If the two grammars both defined `include_module`, but differently, that would not be the case.

**Comment by nbacquey** [comment]
I'm not sure the query file we currently use is correct, in that regard.
There are 4 instances of `module_path`, 2 of `extended_module_path`, and none of `module_type_path` in the query file. This suggests that there may be cases where a `module_path` might be formatted differently than a `module_type_path`, which we want to avoid

**Comment by torhovland** [comment]
My guess is that we just haven't completed all the patterns yet. Does everything stay green if you let `module_type_path` and `extended_module_path` adopt the rules of `module_path`?

**Comment by nbacquey** [comment]
It doesn't break anything in the `.ml` test file (I guess because `module_type_path` does not appear much in implementation files), but it breaks the test files for interfaces, which are on my [dev branch](https://github.com/tweag/topiary/tree/nb/ocaml_mli)
I will inspect other files that produce different trees, and produce a more comprehensive set of equivalence classes

**Comment by nbacquey** [comment]
Well, in the 2500+ "ambiguous" `.mli` files I found, the only equivalence classes needed are the ones listed above. In that light, I think a simple note listing those in the query file is sufficient.

**Comment by torhovland** [comment]
So the broken tests for interfaces can be fixed?

**Comment by nbacquey** [comment]
They can. I'm drafting a PR which supports `.mli` files with the mechanism discussed above
