### ISSUE TITLE
Nickel formatting support

### ISSUE THREAD

**Issue by thufschmitt** [tweag/topiary#165]
**Is your feature request related to a problem? Please describe.**

[Nickel](https://github.com/tweag/nickel) doesn't have a formatter yet. Now is the right time for it to get one given that it's at an early-enough stage that it could just become the default formatter and remove a whole class of bikeshedding discussions.

**Describe the solution you'd like**

A topiary-based formatter for Nickel

**Additional context**

Nickel already has a [tree-sitter grammar](https://github.com/nickel-lang/tree-sitter-nickel) (although it is slightly outdated if I understand correctly), and the OCaml queries could (hopefully) be adapted for Nickel since the languages are somewhat similar.

**Comment by yannham** [comment]
FYI, there are three open PRs in the `tree-sitter-nickel` which updates the grammar to 0.3.1 (https://github.com/nickel-lang/tree-sitter-nickel/pull/12, https://github.com/nickel-lang/tree-sitter-nickel/pull/13, https://github.com/nickel-lang/tree-sitter-nickel/pull/14). Might be interesting to update the formatter once they land.
