### ISSUE TITLE
Use Topiary as a library in some client application

### ISSUE THREAD

**Issue by ErinvanderVeen** [tweag/topiary#166]
We currently only test Topiary as a binary. In order to show the validity of using Topiary as a library in some other application, it would be worth trying this out. With #165 being actively worked on it might be worth considering Nickel as a candidate (also written in Rust t.ex).

Another other project would also work.

**Comment by torhovland** [comment]
I believe this is the same as #137.

**Comment by ErinvanderVeen** [comment]
Right, thank you.
