### ISSUE TITLE
topiary.tweag.io Interactive Playground

### ISSUE THREAD

**Issue by Xophmeister** [tweag/topiary#171]
**Is your feature request related to a problem? Please describe.**
To prototype new queries and to play with Topiary as a formatting engine (e.g., to drive adoption), it would be really useful to have an online, interactive playground at, say, topiary.tweag.io (or similar). These are very common in this space: e.g., [Tree Sitter](https://tree-sitter.github.io/tree-sitter/playground), [Shellcheck](https://www.shellcheck.net), [Rust](https://play.rust-lang.org), [Black (third-party playground)](https://black.vercel.app), etc.

**Describe the solution you'd like**
Provide a simple playground website (frontend and backend), with the following widgets:
* Source code input
* Source code grammar selector
* Topiary query input (defaults to the bundled language queries, based on grammar selector)
* Output panel

The output panel would update interactively, on changes to the input widgets.

**Describe alternatives you've considered**
It's quite easy to rig this up in the terminal, for prototyping and playing, but there's a non-zero amount of friction.

**Additional context**
Many playgrounds allow you to save/share state. This would be a "nice-to-have", but not strictly necessary, IMO.

**Comment by Xophmeister** [comment]
Reporting findings, so far, so they don't get lost:

### WASM vs. REST

A REST API would be very easy to write. However, that would then require a long-term commitment on server infrastructure and all that entails.

A WASM target is harder to write, presuming it can be done, but then it can be statically hosted with a trivial maintenance burden.

### Is WASM possible?

The [Tree-sitter playground](https://tree-sitter.github.io/tree-sitter/playground) is using WASM. Also, the [Rust Sitter project](https://github.com/hydro-project/rust-sitter) contains this quote in its `README`:

> _Note: By default, Rust Sitter uses a fork of Tree Sitter with a pure-Rust runtime to support `wasm32-unknown-unknown`. To use the standard C runtime instead, disable default features and enable the `tree-sitter-standard` feature_

That highly suggests that, not only is it possible, but gives two departure points to see how it's done.

### Notes and Resources

* [Rust and WebAssembly](https://rustwasm.github.io) \
  This contains a bunch of resources, including a [book](https://rustwasm.github.io/docs/book/). It was a struggle to get the book exercises to work as described -- things have moved on, since it was written -- but it's possible, albeit leaving one with a somewhat unsatisfied feeling from the superficial understanding.

* Nix\
  Getting the Rust WASM book exercises to work with Nix was a particular challenge. [This gist](https://gist.github.com/573/885a062ca49d2db355c22004cc395066) helped, but may also be subject to drift. There is also [tweag:rust-wasm-nix](https://github.com/tweag/rust-wasm-nix)...

**Comment by torhovland** [comment]
Looking a bit more into what [Rust Sitter](https://github.com/hydro-project/rust-sitter) does, I don't think it applies to us.

They are using the tool [C2Rust](https://c2rust.com/) to transpile Tree-sitter to Rust code. It then becomes easy to build Wasm using `cargo build --target wasm32-unknown-unknown`. 

We could have done the same, but the problem is all the various Tree-sitter grammars that also have to build C code as well as depend on the Tree-sitter crate. Rust Sitter doesn't have that problem, because they don't depend on any grammars. They are a tool for creating grammars.

The Tree-sitter crate actually consumes grammars as C code. Reworking this as well as all the grammars to Wasm sounds non-trivial.

Will now take a look at how the Tree-sitter playground works.

**Comment by torhovland** [comment]
The [Tree-sitter Playground](https://tree-sitter.github.io/tree-sitter/playground) is nice because it is built as one `tree-sitter.wasm` file without the grammars. And each time you select a language from a drop-down list, a corresponding `tree-sitter-<language>.wasm` is downloaded.

**Comment by aspiwack** [comment]
Let me point out that @TerrorJack has extensive experience with Wasm, in particular with compiling C code with Wasm. So don't hesitate to ask him for advice.

**Comment by torhovland** [comment]
I think the way to do this would be something like this:

- Make Tree-sitter and all the grammars optional dependencies, so we can compile without them when building Wasm.
- Replace the calls to Tree-sitter and grammars with stubs so the code compiles.
- Replace the stubs with target-specific (if Wasm) bindings to some Javascript glue code that can invoke code from the Tree-sitter and grammar Wasm modules.

That's the general idea, anyway. Will update this strategy when I know why it doesn't work 😀

**Comment by torhovland** [comment]
A basic version is now implemented and deployed to https://topiary.tweag.io/playground. Let's log any suggested improvements as separate issues.

**Comment by torhovland** [comment]
Follow-up issues are logged in #356, #357, #358, #359, #360, #361, #362, and #365.

@Xophmeister Can we close this issue?

**Comment by Xophmeister** [comment]
Definitely :+1:
