### ISSUE TITLE
[OCaml] Simplify multiple indentation when possible

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#188]
**Describe the bug**
Multiple, nested indented blocks that start and end at the same points are not simplified. For instance, this is the output of topiary, with a two-space indentation:
```
let f = fun x ->
    x + 1
```

**Expected behavior**
In the example above, I expect the output to be
```
let f = fun x ->
  x + 1
```

**Environment**
 - Ubuntu 22.04
 - main on 2023-01-24 (https://github.com/tweag/topiary/commit/3eefa610bab865a25adaf93a1046937b85836657)

**Comment by torhovland** [comment]
In short, because both a multi-line `let` block and a multiline `function` initiate an indentation each.

**Comment by aspiwack** [comment]
Ah, and we don't really see it because the `fun x ->` hangs, or something like this. Interesting. What are the queries involved?

**Comment by torhovland** [comment]
```scheme
; Make an indented block where a function type arrow starts. Only for the root
; level, not for each arrow.
;
; (?used_slot:bool ref ->
;   Longident.t loc ->
;   Path.t * Env.t)
;
(constructed_type
  (function_type
    "->" @append_indent_start
    (_) @append_indent_end
    .
  )
)

; Indent and allow softlines in multiline function definitions, such as
; let long_function
;   (long_argument_1: int)
;   (long_argument_2: int)
;   (long_argument_3: int)
;   (long_argument_4: int) =
;   ()
(let_binding
  .
  (_) @append_indent_start
  (_) @append_indent_end
  .
)
```

**Comment by torhovland** [comment]
I think the solution here is to simplify consecutive indentation markers in post-processing while ignoring any whitespace between each, just like we do for consecutive spaces and line breaks.

**Comment by aspiwack** [comment]
I'm not so sure about this.

What is the expected indentation of

```ocaml
let f :
  a
  long
  type
  = fun x ->
    some content
```

I indented it twice here. Is this what we want?

**Comment by nbacquey** [comment]
According to the guidelines drafted in #219, I think the expected indentation for this code block would be
```ocaml
let f :
    a
    long
    type
  = fun x ->
    some content
```

**Comment by aspiwack** [comment]
Ah, and what about

```ocaml
let f
  many
  long
  argument
  names
  =
    some content
```

This is also something to think about.

**Comment by aspiwack** [comment]
@nbacquey I think that your answer indirectly pleads for not eliminating double-indentations, doesn't it?

**Comment by torhovland** [comment]
@aspiwack We would only simplify/deduplicate indentation blocks that are identical. For blocks that start at the same location, but end at different locations, we would not simplify, so that should take care of your last example.

You make a good point about when you change:

```ocaml
let f :
    a
    long
    type
  = fun x ->
    some content
```

to

```ocaml
let f = fun x ->
    some content
```

I would be inclined to disregard the diff-minimising principle in this case, but I understand that may be controversial.

**Comment by aspiwack** [comment]
There is no free lunch. Some properties will sometimes break.

But I'm inclined to say that if the simplest is better from a diff-minimisation perspective, then we may want to favour simplicity.

**Comment by nbacquey** [comment]
As per the comment above, I think we can keep the current situation.
