### ISSUE TITLE
[OCaml] Bad formatting of multiline lists

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#189]
**Describe the bug**
Formatting of multiline lists is quite poor. This is the output of topiary:
```
let _ =
  [1 ;
  2 ;
  3]
```
**Expected behavior**
I would expect the example above to be formatted in either one of those:
```
let _ = [
  1 ;
  2 ;
  3
]
```
```
let _ =
  [ 1
  ; 2
  ; 3
  ]
```
```
let _ =
  [
    1 ;
    2 ;
    3
  ]
```
```
let _ =
  [ 1 ;
    2 ;
    3
  ]
```

**Environment**
 - Ubuntu 22.04
 - main on 2023-01-24 (https://github.com/tweag/topiary/commit/3eefa610bab865a25adaf93a1046937b85836657)

**Comment by aspiwack** [comment]
I'd add: terminating semicolon:

```ocaml
let _ = [
  1;
  2;
  3;
]
```
