### ISSUE TITLE
[OCaml] Line breaks in module types

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#191]
**Describe the bug**
In interface files, we are too eager to put line breaks before the `sig` keyword. For instance, this common piece of code:
```ocaml
module Foo: sig
  val foo : int
end
```
gets formatted as
```ocaml
module Foo:
sig
  val foo : int
end

```

**Expected behavior**
I expect the original formatting to be kept as is.

**Environment**
 - Ubuntu 22.04
 - main on 2023-01-24 (https://github.com/tweag/topiary/commit/3eefa610bab865a25adaf93a1046937b85836657)

**Comment by aspiwack** [comment]
How easy is it to fix this?

**Comment by torhovland** [comment]
This is likely easy. In short, drop the current line break, then put back a more specific line break where the tests fail.
