### ISSUE TITLE
Softline-like predicates for list/tuple/record delimiters

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#199]
It is customary to add a delimiter after the last element of a list/tuple/record, when the grammar allows it and the context is multi-line: it minimizes the diff when adding an element at the end of the collection.
However, it is unusual to see one when the context is single-line.

The following two pieces of code are formatted correctly:
```ocaml
[1; 2; 3]
```
```ocaml
[
  1;
  2;
  3;
]
```
The following two, less so:
```ocaml
[1; 2; 3;]
```
```ocaml
[
  1;
  2;
  3
]
```
In order to produce only the first two outputs, we would need the ability to produce a delimiter symbol only if the context is multi-line. This would be akin to `@append_empty_softline`, except that we would produce a `;` instead of a line break.

**Comment by aspiwack** [comment]
@torhovland already built this capacity. See #67.

(also, note that in Ocaml, it won't work for tuples. I think. But it does for list and records.)

**Comment by nbacquey** [comment]
Unless I'm mistaken, the `@append_delimiter` predicate cannot distinguish between single-line and multi-line nodes, which is what we need here

**Comment by aspiwack** [comment]
Ah, this is what you meant. I think we should just add the delimiter in both cases, shouldn't we? There is no strong reason either way, but it's simpler to just add the delimiter always. If we didn't add it in the single-line setting, we would want to remove it altogether, since it normalises a micro-decision away. We could do this, but isn't it unnecessarily complex?

**Comment by torhovland** [comment]
This is a tough one. On one hand I agree with @aspiwack's point of view. On the other hand I think the first two code samples at the top look the most agreeable.

**Comment by aspiwack** [comment]
Ok, here is what I suggest: we add the `;` everywhere for v0.1. And we consider further refinement later. What do we think about this?

**Comment by nbacquey** [comment]
Agreed. I'll remove this issue from v0.1 and amend #198

**Comment by aspiwack** [comment]
Don't amend: merge #198 and make a separate PR.

**Comment by nbacquey** [comment]
I have reconsidered: allowing `[1; 2; 3;]` breaks formatting elsewhere. Fixing it is about as costly as adding this `@append_multiline_delimiter` predicate, so I'm going to do that instead.

**Comment by aspiwack** [comment]
> I have reconsidered. Allowing `[1; 2; 3;]` breaks formatting elsewhere.

How so?

**Comment by nbacquey** [comment]
Well, it's not idempotent: the general rule is that `;` must be followed by a spaced softline, and it makes sense, at least in sequences:
```ocaml
  my_stack#push 1;
  my_stack#push 2;
  my_stack#pop
```
and object signatures:
```ocaml
let obj_with_unit_id (obj : < nothing: unit; .. >) = obj
```
It means that `[1; 2; 3;]` would be formatted as `[1; 2; 3; ]`.

Fixing that would mean to explicitly list all contexts in which `;` must be followed by a spaced softline, and I think the query file is already big enough.

On the other hand, implementing `@append_multiline_delimiter` is just copy/pasting the code for `@append_softline`, sprinkled with a bit of `@append_delimiter`.

Besides, I'm really adverse to seeing `[foo; ]` in the code.
