### ISSUE TITLE
[OCaml] Odd spaces in parenthesized types

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#215]
As of 6f71f36:

### Snippet 1

The following
```ocaml
type query = (string * string list) list
```
gets formatted as
```ocaml
type query = (string * string list ) list
```
(This also happens without `string *`, even if I would probably then not use parentheses.)
(This also happens without the first `list`.)

### Snippet 2

The following
```ocaml
type x = ('any Slug.t -> bool) -> float
```
gets formatted as
```ocaml
type x = ( 'any Slug.t -> bool) -> float
```
(This does not happen without `'any`.)

**Comment by Xophmeister** [comment]
Minimal examples to reproduce:
```ocaml
type t = (x) x
type t = ('x -> x)
```

In the first instance, we have:
* `(type_definition)`
  * Anonymous `type`
  * `(type_binding)`
    * `(type_constructor)`
    * Anonymous `=`
    * `(constructed_type)`
      * Anonymous `(`
      * `(type_constructor_path)`
        * `(type_constructor)`
      * Anonymous `)`
      * `(type_constructor_path)`
        * `(type_constructor)`

In the second instance:
* `(type_definition)`
  * Anonymous `type`
  * `(type_binding)`
    * `(type_constructor)`
    * Anonymous `=`
    * `(parenthesized_type)`
      * Anonymous `(`
      * `(function_type)`
        * `(type_variable)`
        * Anonymous `->`
        * `(type_constructor_path)`
          * `(type_constructor)`
      * Anonymous `)`
