### ISSUE TITLE
[OCaml] Odd indentation in type definitions

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#216]
As of https://github.com/tweag/topiary/commit/6f71f3678970023c45be593350221aa8873915e7

### Snippet 1

The following
```ocaml
type controller = Slug.t ->
    controller
```
gets formatted as
```ocaml
type controller =
Slug.t ->
controller
```

### Snippet 2

The following
```ocaml
type controller =
  | C : Slug.t ->
      controller
```
gets formatted as
```ocaml
type controller =
  | C :
    Slug.t ->
      controller
```
with a peculiar indentation of this `controller` result. Intended?

### Bonus: snippet 2'

The apparently multiline
```ocaml
type controller =
  | C : Slug.t -> controller
```
gets formatted as
```ocaml
type controller = | C : Slug.t -> controller
```
(I'd have expected it to stay multiline.)

### Bonus: snippet 2''

The same as 2 without `|`
```ocaml
type controller =
    C : Slug.t ->
      controller
```
gets formatted as
```ocaml
type controller = C :
    Slug.t ->
      controller
```
(And the `C` went away :'( )

**Comment by Niols** [comment]
I would say P2 for snippet 1, and P3/P4 for snippets 2, 2' and 2''.

**Comment by nbacquey** [comment]
As far as I can tell, the extra indentation is intended in snippet 2, it looks better on things like
```ocaml
  | Zk_rollup_update :
    {
      zk_rollup: Zk_rollup.t;
      update: Zk_rollup.Update.t;
    } ->
      Kind.zk_rollup_update manager_operation
```
