### ISSUE TITLE
[OCaml] Idempotency errors on PPX tags in records' last field

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#224]
As of 73f3995, which in particular is after #223 which closes #220, the following:

```ocaml
type t =
  { foo : bool;
    bar : float [@default false] [@key "baaar"] }
```
yields an idempotency check failure caused by a parsing error in the second round. With `--skip-idempotency`, the result is
```ocaml
type t = {
  foo: bool;
  bar: float [@default false]; [@key "baaar"];
}
```

This does not happen when the last field is also terminated by a semi-colon. For instance
```ocaml
type t =
  { foo : bool;
    bar : float [@default false] [@key "baaar"]; }
```
is formatted just fine.

**Comment by nbacquey** [comment]
Ah, so
```scheme
(
  (field_declaration)
  .
  (attribute)+ @append_delimiter
  .
  ";"* @do_nothing
  (#delimiter! ";")
)
```
appends a delimiter after each `attribute`, not the group as a whole. Well, TIL.

**Comment by torhovland** [comment]
Yep 😄 

(I should have caught that in review.)
