### ISSUE TITLE
[OCaml] Spacing around list concatenation

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#232]
As of c22f8d5, the following
```ocaml
let rec map f = function
  | [] -> []
  | x :: xs -> f x :: map f xs
```
gets formatted as
```ocaml
let rec map f = function
  | [] -> []
  | x::xs -> f x::map f xs
```
I would have expected it to remain the same, with spacing around `::`. Some people like the absence of spacing, in particular in short patterns such as `x::xs` (or when matching on a pair of lists, `x::xs, y::ys`). However, I believe we should add spacing around `::` for two reasons:
- by consistency with the other operators, for which Topiary adds spacing (eg. arithmetic operators).
- because it makes some things less readable otherwise: my brain would parse `f x::map f xs` instinctively as four tokens, `f`, `x::map`, `f` and `xs`.

**Comment by Xophmeister** [comment]
I'm not an OCaml person, so bear with me...

The current rules for the `::` operator are very few:
1. Certain elements[^1] are space-separated, _unless_ they are interposed by a `::`;
2. Spacing around `::` is added when it follows a labelled argument (e.g., `foo ~arg :: []`).

In your example, the `::` appears as a child to the `(cons_pattern)` and `(cons_expression)` nodes; I don't know if they occur elsewhere, but I suspect not. If I were to naïvely add spaces around them wherever, that would flaunt some instances of the first rule.

So the question is: Are there any instances where it's idiomatic to _not_ surround `::` with spaces? If not, then the first rule, above, can be relaxed (imo).

[^1]: https://github.com/tweag/topiary/blob/a204fe87420f8eaf62cd2bc892d9d6397c439d33/languages/ocaml.scm#L403-L477

**Comment by Xophmeister** [comment]
For an idea of the effect of doing this see, e.g., https://github.com/tweag/topiary/pull/234/files#diff-4b9fd3e2640276ee705e5851f570dca4d2cf44e2884a6c3038ed788cb3a84a85

I'll let OCaml people comment on whether this is desirable...

**Comment by Niols** [comment]
> Are there any instances where it's idiomatic to not surround `::` with spaces?

I would say it is rather common to see list patterns use very short variables and no space around variables, eg.
```ocaml
let rec length = function
  | [] -> 0
  | h::t -> 1 + length t
```

Then I sometimes put no spaces to make it a shorter argument of a function, eg.
```ocaml
let rec rev acc = function
  | [] -> acc
  | h::t -> rev (h::acc) t
```
where the spacing helps “parsing” (visually, I mean) the last line as three tokens, `rev`, `h::acc` and `t`. But this argument would apply to other operators, eg. when arguments are `i+1`. That being said, the alternative
```ocaml
let rec rev acc = function
  | [] -> acc
  | h :: t -> rev (h :: acc) t
```
is not per se harder to read.

I would be in the team of just adding spaces everywhere. In your link above, I think there is maybe one instance where I'm like “oh I would not have added the space there”, but all the others improve the situation imo.

**Comment by Xophmeister** [comment]
There's been no visceral reaction from OCaml people (yet :sweat_smile:), so I've submitted the PR for review.

**Comment by nbacquey** [comment]
I'm not opinionated on either spacing policy, so let's go with this modification
