### ISSUE TITLE
[OCaml] Indentation of `function` and `match` cases in PPX syntax

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#233]
As of c22f8d5, the following
```ocaml
let x =
  [%expr function
    | false -> 0.
    | true -> 1.]
```
gets formatted as
```ocaml
let x =
  [%expr function
  | false -> 0.
  | true -> 1.]
```
losing the indentation. I would have expected it to remain the same, probably.

---

As for `match`, the following
```ocaml
let x =
  [%expr match x with
    | false -> 0.
    | true -> 1.]
```
gets formatted as
```ocaml
let x =
  [%expr
  match x with
  | false -> 0.
  | true -> 1.]
```
I would have expected it to remain the same or, if one insists to have `match` not go on the line of the `[%expr`, the I would expect this
```ocaml
let x =
  [%expr
    match x with
    | false -> 0.
    | true -> 1.]
```
with indentation anyways.

**Comment by Xophmeister** [comment]
I don't think I can get the `match` to avoid the line break, but I can get this:
```ocaml
let x =
  [%expr
    match x with
    | false -> 0.
    | true -> 1.]
```
