### ISSUE TITLE
Handling of indentation for modules with a `with`

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#248]
As of f97a163, the following
```ocaml
module MFloat : SERIALISABLE
  with type t = float =
struct
  type t = float [@@deriving yojson]
  let _key = "float"
end
```
gets formatted as
```ocaml
module MFloat: SERIALISABLE with
  type t = float = struct
  type t = float [@@deriving yojson]
  let _key = "float"
end
```
I think this yields the same considerations as #219 in term of readability: the `struct` gets lost, and the `type t = float` from the `with` statement can get confused for a declaration in the module.

In a similar vain, I am not very convinced by 
```ocaml
module MOption
  (A: SERIALISABLE)
  : SERIALISABLE = struct
  type t = A.t option [@@deriving yojson]
  let _key = A._key ^ "-option"
end
```
with no visual clue about when module argument/types end and when the module definition starts.

**Comment by Xophmeister** [comment]
As of f7d10042b7cbdcf1 (`main`, as of writing), this gets formatted as:

```ocaml
module MFloat: SERIALISABLE with
    type t = float = struct
  type t = float [@@deriving yojson]
  let _key = "float"
end
```
