### ISSUE TITLE
Space/newline separating sequence and PPX extension, eg. `;%lwt` -> `; %lwt`

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#265]
As of 0b5ecc8b1a23cb33a2b9dc2c1e9db1c1a357d45f, the following
```ocaml
let x = foo;%lwt bar

let x =
  foo;%lwt
  bar

let x =
  foo
    bar;%lwt
  baz
```
gets formatted as
```ocaml
let x = foo; %lwt bar

let x =
  foo;
  %lwt
  bar

let x =
  foo
    bar;
  %lwt
  baz
```
Note the extra space after `foo;` in the first snippet and the newline in the second. I would expect these snippets to remain the same.

I would consider it a regression introduced by https://github.com/tweag/topiary/commit/543e05d944829efa26558e78d49ee61327af9720.

**Comment by nbacquey** [comment]
I'm not that familiar with ppx ; do you mean that `;%lwt` is a single semantic unit?

**Comment by Niols** [comment]
Yes, it is the sequence in the lwt syntax extension. `a ;%lwt b` is
equivalent semantically to `[%lwt a; b]`, that is an lwt syntax extension
expression whose payload is a sequence of `a` and `b`. This should show up
in the grammar in some way, probably with a payload being a pstr_eval of a
pexp_sequence (if I follow OCaml Parsetree's naming conventions).

I'm writing from my phone so sorry about the formatting but I can hop in a
call to talk some more about this if needed!
