### ISSUE TITLE
Change of semantics on types with a hash (was: Idempotency error on types with a hash)

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#266]
Frankly, I don't even know what that OCaml construct is supposed to do. However, as of 0b5ecc8b1a23cb33a2b9dc2c1e9db1c1a357d45f, the following
```ocaml
let foo : #y z = bar
```
triggers and idempotency error because the first pass formats it as
```ocaml
let foo : #yz = bar
```
removing the space (and therefore changing the semantics).

**Comment by Niols** [comment]
We might decide that it is less important than `P1` because, even if it is an idempotency error, I think this feature is extremely rare.

**Comment by Niols** [comment]
Actually, I am wrong because I minimised my example too much. The above snippet does not trigger an error in the idempotency check, because it is idempotent. However, the semantics changes between the input and the output. This makes me wonder whether there couldn't be another kind of idempotency check trying to see whether the ASTs are the same during the first and second parsing (up to changes in the location of objects).

**Comment by nbacquey** [comment]
In my opinion this is **very** P1, even P0, because it can silently change the semantics of the code. We never want to do that ; I'm fixing this asap
