### ISSUE TITLE
Generate the usage documentation in the README

### ISSUE THREAD

**Issue by Xophmeister** [tweag/topiary#277]
The usage documentation, in the `README`, is just a lightly-edited version of the usage documentation produced by the `--help` option. This requires consistent effort to avoid divergence.

Generating this automatically with, say, a commit hook or as part of the CI would remove that ongoing maintenance cost.

(n.b. This could also apply to the lists of supported vs. experimental languages in the `README`.)

_Originally posted by @aspiwack in https://github.com/tweag/topiary/pull/272#discussion_r1101855212_

**Comment by torhovland** [comment]
A simple first step that avoids divergence could be a CI step that runs `cargo run --help` and verifies that the output is found in `README.md`.
