### ISSUE TITLE
Enforce an opinion about optional `|` before first match case

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#281]
I think Topiary should be opinionated on whether we should put the optional `|` before the first match case in a pattern matching expression.

I would argue that the following two snippets are correctly formatted:
```ocaml
let not = function true -> false | false -> true
```
```ocaml
let not = function
  | true -> false
  | false -> true
```
While the following two are not:
```ocaml
let not = function | true -> false | false -> true
```
```ocaml
let not = function
  true -> false
  | false -> true
```

In order to only allow the first two snippets, we need two capabilities:
* produce a symbol only in a multi-line context (which `@append_multiline_delimiter` does),
* delete a symbol only if the context is single-line (which we cannot currently do).

**Comment by Niols** [comment]
I agree with both the idea that Topiary should be opinionated about this and the suggestion to never have `|` in single-line pattern-matches and always have `|` in multi-line ones.
