### ISSUE TITLE
Separate library and binary code

### ISSUE THREAD

**Issue by Xophmeister** [tweag/topiary#303]
In aid of #295, all the binary-related code should be moved to the binary crate, making a clear separation from the library code. (For example, the library doesn't really need to be doing filesystem-level IO, it can just provide a `Read` interface, or similar. Therefore, the IO error handling, etc. can be moved into the binary crate.)

**Comment by torhovland** [comment]
@Xophmeister Does #368 resolve this?

**Comment by Xophmeister** [comment]
LGTM :100:
