### ISSUE TITLE
Idempotency errors

### ISSUE THREAD

**Issue by torhovland** [tweag/topiary#334]
**Describe the bug**
The sample tester has had its idempotency check turned off by mistake, and it turns out we have some idempotency errors in our test files.

**To Reproduce**

```
cargo run -- -f tests/samples/input/ocaml.ml
cargo run -- -f tests/samples/input/bash.sh
```

**Expected behavior**
Green tests after idempotency check has been enabled.

**Actions**

- [x] Fix OCaml errors. (done in #339)
- [x] Fix Bash errors.
- [x] Enable idempotency check in `input_output_tester` and `formatted_query_tester`.

**Comment by Xophmeister** [comment]
The Bash idempotency problem is due to #200, IIRC. I think this probably requires an upstream fix to the grammar; so the best I can do for now is just remove the offending code, as Bash support is still experimental.

**Comment by torhovland** [comment]
@Xophmeister Sounds reasonable. Can you do that, and then get this issue completed?
