### ISSUE TITLE
Rewrite `detect_line_breaks_inner`

### ISSUE THREAD

**Issue by torhovland** [tweag/topiary#346]
**Is your feature request related to a problem? Please describe.**
This function has become a mess. Rewrite it, preferably in a functional style without mutable variables.

**Describe the solution you'd like**
A reimplementation that is easy to read.

**Comment by Xophmeister** [comment]
This is indeed hard to understand! I believe the tl;dr of what this function is doing is something like:

> In a depth-first traversal of the syntax tree, if the number of new lines between the current and previously visited node meets (or exceeds) the threshold, then:
> * Add the current node (ID) to the "before" set
> * Add the previous node (ID) to the "after" set
>
> (If the current node is the root, then we skip the comparison and proceed to the next node in the traversal.)

The most obvious (IMO) functional-style refactor would therefore be to:
* Flatten the tree, depth-first $\Rightarrow$ Vector of nodes
* Zip this with its own tail $\Rightarrow$ Vector of node pairs\
  (This represents adjacent nodes per the DFS, 1 element shorter than the flattened tree vector)
* Filter this by the threshold distance between pair components $\Rightarrow$ Vector of node pairs
* Unzip into the "after" and "before" sets, respectively $\Rightarrow$ Pair of sets

Likely frustrations:
* Ownership and/or borrowing constraints.
* If we can't use `&Node`, then Tree-Sitter's API will make it difficult for us to, e.g., look up nodes by their private ID.
