### ISSUE TITLE
Put some content and styling on the web site at topiary.tweag.io

### ISSUE THREAD

**Issue by torhovland** [tweag/topiary#355]
**Is your feature request related to a problem? Please describe.**
A very basic web site is deployed at topiary.tweag.io, but it needs some content and styling.

It doesn't need a lot, but this would probably be nice:

- A short introduction to Topiary.
- How to install and run.
- A prominent link to the playground.
- Link to GitHub.
- GitHub badges.
- Link to blog post.
- Link to Tweag.
- Link to Tree-sitter.
- Later: link to crate, and to various package repositories.

**Describe the solution you'd like**
A nice web page.

**Additional context**
See the following for inspiration:

- https://nickel-lang.org
- https://tree-sitter.github.io

**Comment by aspiwack** [comment]
For the website's design and possibly a logo too, we may get some help from the Marketing Department. I'll get in touch with them to see what's possible.
