### ISSUE TITLE
Automated testing of Wasm playground

### ISSUE THREAD

**Issue by torhovland** [tweag/topiary#365]
**Is your feature request related to a problem? Please describe.**
As grammars and Topiary code evolves separately, we are bound to break the playground at some point. We need automated tests to cover this.

**Describe the solution you'd like**
Either unit tests against the Wasm code, or GUI tests (e.g. Cypress) against the web playground, or both.

**Comment by nbacquey** [comment]
The fact that grammars and Topiary code evolve separately is also a potential break for the CLI, and I think our tests should already catch such errors.

Do you have an example of a divergence between grammar and Topiary code that could not (should not?) be caught by the tests we already have?

That being said, having tests for the Wasm code is a good idea in general, I'm just not convinced we are threatened by divergences between grammars and Topiary code specifically, as those should be handled in the library.

**Comment by torhovland** [comment]
The problem is when somebody updates a grammar crate (e.g. `tree-sitter-nickel = { git = "https://github.com/nickel-lang/tree-sitter-nickel" }`) without being aware that the Wasm grammars (e.g. `web-playground/public/scripts/tree-sitter-nickel.wasm`) are completely separate from this.

So if (when) a grammar crate introduces major changes, and our query files are updated to be compatible with the new grammar, the playground will stop working.

How to update the Wasm grammars is [described here](https://github.com/tweag/topiary/blob/main/CONTRIBUTING.md#web-site-and-web-playground).

**Comment by torhovland** [comment]
This already happened 😅
#393
