### ISSUE TITLE
Integration tests fail if errant files exist in the sample directories

### ISSUE THREAD

**Issue by Xophmeister** [tweag/topiary#390]
**Describe the bug**
The integration tests crash if a file exists in `topiary/tests/samples/input` that it doesn't understand. This can happen if, for example, you are editing a test and your editor places a swap/undo file alongside it.

**To Reproduce**
With Vim:
* Open any file in `topiary/tests/samples/input`. Under normal configuration, Vim will create a swap file alongside it (e.g., `.whatever.swp`).
* Run the integration test suite.

This probably happens with other editors (e.g., I believe Emacs creates `whatever~` sibling files under normal configuration).

**Expected behavior**
Skip over editor artefacts, or unknown files. Although that then raises the question: What's good and what's not? Perhaps only matching files in `topiary/tests/samples/expected` would be a first start...although if you were editing both simultaneously -- which is likely -- the same problem may occur!

**Environment**
 - OS name + version: NixOS 22.05
 - Version of the code: a26a870

**Additional context**
In Vim, you can work around the problem by using the `-n` switch to not create swap files. (Or, Vim can be configured to keep swap files elsewhere.) Presumably other editors have similar facilities.

**Comment by amanx123** [comment]
I would like to work on this, please assign me !

**Comment by Xophmeister** [comment]
Thanks for your interest, @amanx123 

The Topiary team haven't prioritised this, so please feel free to address it. We look forward to your PR :slightly_smiling_face:
