### ISSUE TITLE
Nickel: else..if formatting

### ISSUE THREAD

**Issue by Xophmeister** [tweag/topiary#399]
In a chain of `if..then..else` expressions, it would be better _not_ to break the line and increase the indent level at each expression. That is, rather than:

```nickel
if ... then
  ...
else
  if ... then
    ...
  else
    if ... then
      ...
    else
      ...
```

We'd have:

```nickel
if ... then
  ...
else if ... then
  ...
else if ... then
  ...
else
  ...
```

([Discussion](https://github.com/tweag/nickel/pull/1198#discussion_r1150806010))

**Comment by yannham** [comment]
By the way, I think this is something showing up in OCaml as well, and any expression-oriented language without a dedicated `else if` construct. Do you know how topiary currently handles this for OCaml?

**Comment by Xophmeister** [comment]
The way it's done for OCaml should apply to Nickel, too. Topiary has an "ignore this rule" directive, that can be applied when certain nodes are present. It should therefore just be a case of using that, with potentially some refactoring to ensure the cancellation covers everything.

That's why I'm cautiously optimistic :crossed_fingers:
