### ISSUE TITLE
Dynamic loading of language support

### ISSUE THREAD

**Issue by torhovland** [tweag/topiary#4]
Don't link statically to `tree-sitter-json` and future languages. Investigate how https://github.com/helix-editor/helix does it.

With our push to publish on crates.io this issue regains more importance, we cannot depend on git dependencies, nor can we publish all tree-sitter grammars to crates.io ourselves.

**Comment by Xophmeister** [comment]
See #595 for a discussion on also pulling the queries from upstream.

**Comment by adrian-gierakowski** [comment]
Are there any plans to address this in the near future? Thanks!

**Comment by ErinvanderVeen** [comment]
No, you're right. This issue can be closed.
