### ISSUE TITLE
Only show the differences when an integration test fails

### ISSUE THREAD

**Issue by Xophmeister** [tweag/topiary#401]
**Is your feature request related to a problem? Please describe.**
When an integration test fails -- in the case of the output not matching the expected output -- then the full, colourised diff is printed. Given that the integration test input files are _very_ large, but the difference can be isolated to single lines, it can be difficult to page through the output to find the formatting errors.

**Describe the solution you'd like**
Only output the changes, not the code that is invariant under formatting.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Xophmeister** [comment]
I prefer the colours, too... Maybe an alternative could be to add an option to `pretty_assertions` to show context lines (defaulting to all) and fix the issue upstream?

**Comment by nbacquey** [comment]
`pretty_assertions` works on a whole variety of structures. Printing only the diff and some context in this general case seems like a difficult problem to me, maybe one we don't want to address yet.
I think I'll add the alternative you suggest in the text tools of [`prettydiff`](https://github.com/romankoblov/prettydiff) instead, which has a much smaller scope.
