### ISSUE TITLE
Consistent formatting of bound expressions

### ISSUE THREAD

**Issue by yannham** [tweag/topiary#422]
**Is your feature request related to a problem? Please describe.**

There are mainly two ways to bind expression to names in Nickel: let-binding and record definitions. Of course, the two are different and used in different contexts, but they are morally part of the same schema, and share (at least partially) common syntax, in particular around annotations.

However, they are formatted differently:

```nickel
let foo = {
    bar = 1,
    baz = 2,
} in
{
  foo = {
    bar = 1,
    baz = 2,
  }
}
```

is reformatted to

```nickel
let foo =
  {
    bar = 1,
    baz = 2,
  }
in
{
  foo = {
    bar = 1,
    baz = 2,
  }
}
```

We can see that a multiline let-expression _always introduce a new line and identation level_ for the bound expression (the record inside `foo`), but a record field doesn't. There was a lengthy conversation with @Xophmeister, and one reason for the current behavior is that this avoid adding to many indentation levels when defining record fields: when coupled with metadata (which already introduces a level of indentation for the `=` sign), we can indeed quickly go far to the right when defining nested records.

**Describe the solution you'd like**
The question of "should we add a new line or not" after a binding is an interesting one (and isn't clear-cut), but whatever we choose, I think the formatting of let-bound expressions and fields should be consistent and follow the same rules, as there doesn't seem to be a good reason why an argument for one style or the other would only apply to let-bindings and not record fields, or vice-versa.

After a more in-depth discussion with the Nickel team, we identified that the default should be to add a new line and a new indentation level (that is, following the current style of let-bindings). **However**, with the following exceptions, which are very common idioms and could inflate the indentation of the whole file unduly :

- if the next element is a record literal `{ .. }`, then don't add a new line (so, in the end, the previous example would in fact be formatted in the style of the the record field, and not the let-binding)
- if the child element is a function declaration (it's customary in ML to even have the argument to the left of the equal sign: while this syntax isn't valid in Nickel, it's still customary to write `let foo = fun x y z => ...`)
- if the child element is an array literal
- if the child element is a match statement
- if the child element is a expression inside parentheses

**Comment by yannham** [comment]
@aspiwack I guess not, because they currently have a different treatment (at least in the tree-sitter grammar, and they are surely not in the LALRPOP grammar). I wonder if this feasible, due to the following differences:

- fields can be specified as paths: `{foo.bar.baz = false}`
- field can hold metadata that aren't allowed anymore in a let-binding position: `{foo | force = 1}`
- the LHS of the `let LHS = RHS in body` let-binding can be a pattern: `let {foo, bar=baz} = value in ...`

And maybe other differences that I forgot. Perhaps they can still be factorized in a very generic rule, but I wonder if that rule wouldn't feel a bit artificial, given those differences.

**Comment by Xophmeister** [comment]
@yannham Presumably an enum literal (`[| ... |]`) is also a similar exception?

**Comment by yannham** [comment]
> Ah yes, I forgot that one. And I guess multiline strings fit the bill as well. In the end, I think any kind of delimited block fits the bill, with delimiters being (, {, [, [|, and m%" (as well as symbolic strings xxx-s%").

I would say that we also have to ensure that the content of the block is indented, but I think this is always the case in practice for those blocks (as long as they are multiline).

**Comment by Xophmeister** [comment]
> (as well as symbolic strings `xxx-s%"`)

I don't think these are covered by the Tree-sitter grammar yet (AFAIK).

**Comment by yannham** [comment]
@Xophmeister I think they are, on the unstable branch? But my impression was that you targeted the unstable branch by default, don't you?

**Comment by Xophmeister** [comment]
My bad -- fat fingers, today :sweat_smile: Yes, you're right, they work fine and are treated under the same node as multi-line strings :+1:

**Comment by Xophmeister** [comment]
I'm making progress :+1: As of 324d2e3, I'm getting this output for record field assignment. I still need to double-check and test `let` bindings.

```nickel
{
  a = 123,

  b = foo && bar || baz,

  c =
    foo
    && bar
    || baz,

  d = foo |> bar |> baz,

  e =
    foo
    |> bar
    |> baz,

  f =
    let x = 1 in
    let y = 2 in
    let z = 3 in
    x + y + z,

  g = (foo),

  h = (
    foo
  ),

  i = [ 1, 2 ],

  j = [
    1,
    2
  ],

  k = { foo = 123 },

  l = {
    foo = 123
  },

  m = [| `foo |],

  n = [|
    `foo
  |],

  o = m%"foo"%,

  p = m%"
    foo
  "%,

  q =
    [
      1,
      2
    ]
    @ [3]
    @ [4],

  r = fun x => x,

  s = fun x =>
    x
}
```

**Comment by yannham** [comment]
Hey, unless I'm doing something wrong, this doesn't seem to actually be fixed with latest topiary. For example, here is a file formatted by topiary where the behavior between let-binding and record fields definition differ:

```nickel
let Port =
  std.contract.from_predicate
    (
      fun value =>
        std.is_number value
        && std.number.is_integer value
        && value >= 0
        && value <= 65535
    )
in
{
  Port = std.contract.from_predicate
    (
      fun value =>
        std.is_number value
        && std.number.is_integer value
        && value >= 0
        && value <= 65535
    )
}
```

Another one with record literals:

```nickel
let Port =
  std.contract.from_predicate
    (
      fun value =>
        std.is_number value
        && std.number.is_integer value
        && value >= 0
        && value <= 65535
    )
in
{
  Port = std.contract.from_predicate
    (
      fun value =>
        std.is_number value
        && std.number.is_integer value
        && value >= 0
        && value <= 65535
    )
}
```

cc @Xophmeister

**Comment by Xophmeister** [comment]
@yannham I cannot reproduce this with the current `main` (53ef0403). I get the following results:

```nickel
let Port = {
  foo,
  bar,
}
in
{
  Port = {
    foo,
    bar,
  }
}

let Port =
  std.contract.from_predicate
    (
      fun value =>
        std.is_number value
        && std.number.is_integer value
        && value >= 0
        && value <= 65535
    )
in
{
  Port =
    std.contract.from_predicate
      (
        fun value =>
          std.is_number value
          && std.number.is_integer value
          && value >= 0
          && value <= 65535
      )
}
```

Could you please check you're at the right ref (the MD5 of `languages/nickel.scm` should be `efbc9a434f7401be026d49f115cae0e2`)

**Comment by yannham** [comment]
Mmmh, it might have been a `PATH`/`TOPIARY_LANGUAGE_DIR`/Nickel LSP shenanigan. I was sure to have updated, pulled and rebuilt everything, but it seems you're right. I'm sorry for the noise!
