### ISSUE TITLE
help: getting segfaults adding a new language

### ISSUE THREAD

**Issue by BrianHicks** [tweag/topiary#481]
Hey folks! Topiary looks really promising! I decided to try adding Ruby support, just for fun, and I'm having some trouble.

As far as I can tell, I'm following the pattern to add a new grammar but I'm getting a segfault on `RUST_LOG=debug cargo test`. My code is all at https://github.com/tweag/topiary/compare/main...BrianHicks:topiary:ruby. Does it look like I've missed something? Do I need to modify some build script to get things working well?

Running the same command on `main` (2c44a550) seems to be working fine, so it's surely something I've done. 🤔

**Comment by torhovland** [comment]
Hi!

I took a look. If you run just the specific test that fails (`cargo test input_output_tester`), you'll get a better error message:

```
---- input_output_tester stdout ----
thread 'input_output_tester' panicked at '
  1 class Foo; end
    classFoo;end', topiary/tests/sample-tester.rs:12:9
```

And this makes sense, as you haven't added any query patterns that insert spaces yet.

**Comment by torhovland** [comment]
Yes, the test suite shouldn't segfault. We are investigating what is causing that, and will report back within a few days. Feel free to remind us if there is no update.

**Comment by nbacquey** [comment]
The segfault didn't happen in `input_output_tester`, but in `exhaustive_query_tester`. Specifically, that line:
```rust
let match_count = query.matches(root, source, &mut cursor).count();
```
causes a segfault when `query` is empty (or when the query only has one pattern, and it has been disabled).
I'll try to have a minimal reproducer, and open an issue upstream.
In the meantime, #491 circumvents the code and should fix this immediate issue.

**Comment by BrianHicks** [comment]
nice, thank you!
