### ISSUE TITLE
Parse error in Nickel files with wildcard type annotations

### ISSUE THREAD

**Issue by matthew-healy** [tweag/topiary#485]
**Describe the bug**

Trying to format the following file with Topiary:

```ncl
(let { a : { b : Number } = { b }} = { a = { b = "no" }} in
b) : _
```

results in this error:

```
[2023-05-26T09:12:17Z ERROR topiary] Parsing error between line 2, column 4 and line 2, column 7
```

**Expected behavior**

This is valid Nickel, so it should parse (& format) correctly.

**Comment by vkleen** [comment]
I think this is a bug in the tree-sitter grammar; `(fun {x,x} => x) : _` produces a parse error without topiary being involved.
