### ISSUE TITLE
how do you deal with string interpolations?

### ISSUE THREAD

**Issue by BrianHicks** [tweag/topiary#488]
As I mentioned in #481, I'm making a toy formatter for Ruby just to learn how this all works. I have a question about how you'd preserve spaces in interpolated strings.

The Ruby grammar has `string`s with `string_content` and `interpolation` nodes that can live inside them. The `string_content` frequently has whitespace at either end. How do I preserve that? For example, here's an input string:

```ruby
"1 plus 1 is #{2}, 1+1=#{2}"
```

If I have these rules:

```scheme
;; Strings
; Leave spaces alone, except for removing spaces around interpolation delimiters
(string_content) @do_nothing
(interpolation . "#{" @append_antispace)
(interpolation "}" @prepend_antispace .)
```

Then it's formatted like so, when I would want it to be left exactly as it was:

```ruby
"1 plus 1 is#{2}, 1+1=#{2}"
```

(Doing `(string_content) @leaf` does the same thing, by the way.)

Is there a way to turn off formatting within some node, but only for its immediate children? Or to declare that some child gets a pass and that space within the text content of that node should be included? (Examining the nodes with `tree-grepper` shows that this is the case; I've attached it below.) Maybe something with a name like `@append_preserve_whitespace`/`@prepend_preserve_whitespace`?

```console
$ tree-grepper -q ruby '(string_content)' -f pretty-json ./topiary/tests/samples/input/ruby.rb
[
  {
    "file": "./topiary/tests/samples/input/ruby.rb",
    "file_type": "ruby",
    "matches": [
      {
        "kind": "string_content",
        "name": "query",
        "text": "1 plus 1 is ",
        "start": {
          "row": 7,
          "column": 2
        },
        "end": {
          "row": 7,
          "column": 14
        }
      },
      {
        "kind": "string_content",
        "name": "query",
        "text": ", 1+1=",
        "start": {
          "row": 7,
          "column": 20
        },
        "end": {
          "row": 7,
          "column": 26
        }
      }
    ]
  }
]
```

**Comment by ErinvanderVeen** [comment]
Hej, thanks for this issue!

The team is currently on holiday, but I will discuss with them when they return tomorrow!

**Comment by BrianHicks** [comment]
I get an error when I run that: "error: invalid value 'rust' for '--language <LANGUAGE>'". Same if I try with `--language ruby`, which I think you might have meant? I was running it with `cargo run` instead of `topiary` directly, though, although I don't think that should make a difference?

As I've shown above with another tree-sitter tool, the whitespace is included in the `string_content` node in the Ruby grammar. Is that the kind of issue you're thinking about?

**Comment by nbacquey** [comment]
@BrianHicks I did mean `--language ruby` indeed, thanks for noticing. The whitespace is indeed included in the `string_content` node up to the very end of the formatting process.

I managed to track down the source of your issue to #492, we'll work on that.

**Comment by BrianHicks** [comment]
How do you get that `--language` thing to work, though? I see it in the README but it always complains that I'm using an invalid value?

Thanks for finding #492!

**Comment by nbacquey** [comment]
> How do you get that `--language` thing to work, though? I see it in the README but it always complains that I'm using an invalid value?

The `--language` flag is only active for "supported" languages (read "non-experimental"). To enable it, you have to edit the associated `enum` and function in `supported.rs`.
