### ISSUE TITLE
Leaf content trimming is causing unforeseen behaviours

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#492]
In `pretty.rs`, we have the following piece of code:
```rust
            Atom::Leaf {
                content,
                single_line_no_indent,
                ..
            } => {
                // [...]
                write!(buffer, "{}", content.trim_end())?;
            }
```
The `trim_end()` part is the cause of #488: it deletes whitespaces at the end of leaves, even when they are part of the semantics.

The way I understand it, `trim_end()` has been added here to avoid printing leaf nodes containing a single `"\n"` in Bash. I think it would be better to explicitly `@delete` those nodes in the query, instead of silently ignoring them in the pretty-printing phase.
Line breaks are part of the semantics in Bash, I think they ought to be processed with the query mechanism, and the `trim_end()` call should be removed.

@Xophmeister, do you have additional insight on this issue?

**Comment by torhovland** [comment]
It may have been added as a cheap way to get rid of white-space at end of lines. I suggest you try to remove it, and then possibly add a post-processing step or fix some queries to get green tests again.

**Comment by Xophmeister** [comment]
(The post-processing step to remove whitespace at the end of lines [already exists](https://github.com/tweag/topiary/blob/b2399161f60c1eb3404e487b4471ff76455d7a94/topiary/src/lib.rs#L217-L222). As such, you may be able to just remove this `trim_end` with no consequence.)
