### ISSUE TITLE
Document or automate the update process for WASM binaries

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#495]
When writing #494, I once again found myself unable to update the WASM grammar for OCaml, despite the instructions in `CONTRIBUTING.md`. I struggled with Docker configurations, manual ad hoc copy/pastes, and achieved nothing in the end.

I think we need to either automate the process, or make it fool-proof.

**Comment by Xophmeister** [comment]
> I struggled with Docker configurations

I think the process launches a container, rather than you having to run everything inside a container.

That said, I agree: it took a while to work out, the first time I did it. Having it part of the CI build would be ideal, if it can be triggered _only_ when the dependency changes.

**Comment by ErinvanderVeen** [comment]
Resolved with #610
