### ISSUE TITLE
Exporting the query files

### ISSUE THREAD

**Issue by ErinvanderVeen** [tweag/topiary#509]
Other projects that use the topiary library might want to make direct use of the queries shipped with Topiary, as proven by the effort by @vkleen to integrate Topiary into Nickel. These files should be exported and available for users of the library.

**Comment by torhovland** [comment]
Not sure what you mean by exported, but there is `https://doc.rust-lang.org/std/macro.include_str.html`, which can be used to include file contents at compile-time.

Found it via https://users.rust-lang.org/t/packaging-assets-in-a-library-crate/4133.

Will create a sample and see how well it works.

**Comment by torhovland** [comment]
@ErinvanderVeen @vkleen Would the above PR work for you?
