### ISSUE TITLE
Topiary as a git dependency breaks Nix builds with crane

### ISSUE THREAD

**Issue by vkleen** [tweag/topiary#511]
This might be a rather specific failure case, but trying to use Topiary as a git repository dependency breaks Nix builds using [crane](https://crane.dev/). The problem is that in `topiary/src/configuration.rs` there is a `include_bytes!` macro importing `languages.toml` from the workspace root.

When `crane` vendors dependencies, the crates in the workspace end up in the vendor directory separately breaking the workspace structure. In particular, `languages.toml` is lost in the process. This ends up causing mysterious build failures.

It's debatable whether this really is an issue with Topiary. On the face of it, it feels like an issue with `crane`, but they might also be forced into doing this by the structure of a `cargo` vendor directory. I'm also wondering if something like this might lead to problems with publishing the crate to crates.io.

One possible solution would be to move `languages.toml` into the `topiary` subdirectory. I've verified that that fixes the immediate problem.

**Comment by torhovland** [comment]
I have no strong feelings about this. With your recent PR a user should be able to override `languages.toml` with a file under `~/.topiary/`, and as long as that works, it's all good to me.
