### ISSUE TITLE
Idempotency error (and other peculiar behaviours) with `function` inside an `if-then-else` construct

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#529]
**Describe the bug**

On:
```ocaml
let id = if true then Fun.id else function x -> x
```
Topiary produces an idempotency error, the first pass producing:
```ocaml
let id = if true then Fun.id else functionx -> x
```
which is not syntactically correct.

Notes:
- This also happens with more arguments to `function`, eg. `function x -> x | y -> y`.
- This also happens with a multiline `if-then-else`.
- This also happens with a multiline `function`, including with a newline between `function` and `x -> x`.
- This does not happen for `let id = function x -> x`.
- This does not happen for `let id = if true then Fun.id else function | x -> x` and the `|` remains, while it is removed from `let id = function | x -> x`.

**To Reproduce**

```
nix run github:tweag/topiary/cba1993 -- -l ocaml <<EOF
let id = if true then Fun.id else function x -> x
EOF
```
will produce:
```
[2023-06-22T18:13:51Z ERROR topiary] Parsing error between line 1, column 46 and line 1, column 47
```
while its `-s` counterpart will produce:
```
let id = if true then Fun.id else functionx -> x
```

**Comment by torhovland** [comment]
@nbacquey The handling of `let id = if true then Fun.id else function | x -> x` is odd. It contains the following sub-tree:

```
{Node function_expression (0, 35) - (0, 52)} - Named: true
  {Node function (0, 35) - (0, 43)} - Named: false
  {Node | (0, 44) - (0, 45)} - Named: false
  {Node match_case (0, 46) - (0, 52)} - Named: true
```
It should be taken care of by this:

```scheme
(function_expression
  (match_case)? @do_nothing
  .
  "|" @delete
  .
  (match_case)
  (#single_line_scope_only! "function_definition")
)
```

But it doesn't. But if I remove `(#single_line_scope_only! "function_definition")`, it does.

**Comment by nbacquey** [comment]
There was a hint in the debug log:
```
[2023-06-27T09:21:33Z WARN  topiary::atom_collection] Found scoped conditional ScopedConditional { id: 2, scope_id: "function_definition", condition: MultiLineOnly, atom: Literal("| ") } outside of its scope
```
Your diagnosis is right, the `function_definition` scope wasn't applied properly. I'm pushing a fix.

**Comment by ErinvanderVeen** [comment]
Reopened for the other issues mentioned in the issue.

**Comment by Niols** [comment]
I think all the issues that I mentioned are fixed, though.
