### ISSUE TITLE
Pipe operators aren’t stacked in OCaml

### ISSUE THREAD

**Issue by toastal** [tweag/topiary#541]
**Describe the bug**
The pipe operator `|>` is appended to the end of the line which is both unexpected and subjectively makes reading harder. Most folks expect the pipes to line up to show what the next operation is. Visually, putting the pipes at the end makes you read to the end of the line to find the operator when in many cases, you just want to know that the output of one is going to the next so you don’t have to read every implementation to the end; the pipe at the beginning lets you ‘skip’ to the next line if it’s not terribly relevant&mdash;which is likely why almost ever language with pipes line it up this way.

**To Reproduce**
```ocaml
foo
|> bar |> baz
```

formats to

```ocaml
foo |>
  bar |>
  baz
```

**Expected behavior**
```ocaml
foo
|> bar |> baz
```

formats to

```ocaml
foo
|> bar
|> baz
```

or (no strong preference either way)

```ocaml
foo
  |> bar
  |> baz
```

**Environment**
 - OS name + version: NixOS 23.11.20230627.e18dc96 (Tapir) x86_64 
 - Version of the code: topiary-cli 0.2.3

**Comment by Niols** [comment]
I very much agree. This pattern is very common and putting the pipeline operator at the end of the line just never happens.

**Comment by toastal** [comment]
Of note: the Nickel formatting seems to stack the pipe operators as expected.

**Comment by ErinvanderVeen** [comment]
I've looked into this real quick, the issue arises due to the fact that the tree-sitter grammar combines a lot of `rel_operators` into the same node type. So currently operators like `>` are treated identically to `|>`. This isn't the true for Nickel, hence we currently do format pipe operators as expected there.

**Comment by aspiwack** [comment]
Indeed, both the `|>` and `@@` operator should be their own category. Let's make a PR upstream to fix this.

**Comment by aspiwack** [comment]
PS: I realise there's an ambiguity in my claim above. There should be two different named node. One representing exactly `|>` and one representing exactly `@@`.

**Comment by ErinvanderVeen** [comment]
I don't want to bother upstream with something that can be fixed by Queries (until we run into some bigger problems). I'll try to match on "|>" first. If that doesn't work (for whatever reason), we can consider upstream contributions.

**Comment by 314eter** [comment]
The operators are grouped by precedence and associativity (which in most cases is determined by the first character). In most cases you want to format all operators in a group the same way. If someone defines a custom `|>>` operator, it makes sense to format it the same as `|>`.

Does it make sense to format every `rel_operator` (including `|>`) with a linebreak before, and every `concat_operator` (including `@@`) with a linebreak after? That would result in
```ocaml
foo
|> bar
>> baz
<|> quux

foo @
bar @@
baz ^^
quux
```
The main difference between these operators, and the reason you want to format them differently, is that `rel_operator` is left associative, and `concat_operator` is right associative. If you add parentheses, it becomes clear why this is an intuitive way to format them
```ocaml
((((foo)
|> bar)
>> baz)
<|> quux)

(foo @
(bar @@
(baz ^^
(quux))))
```
and this is not
```ocaml
((((foo) |>
bar) >>
baz) <|>
quux)

(foo
@ (bar
@@ (baz
^^ (quux))))
```

**Comment by Niols** [comment]
I think I am rather convinced by the separation between `rel_operator` and `concat_operator`, the former being put at the beginning of lines and the latter at the end.

**Comment by aspiwack** [comment]
Thanks @314eter for the rationale.

I quite enjoy the heuristic of formatting left-associative operators at the start of lines and right-associative operators at the end of lines. I'm not quite convinced it works yet (one reason for doubt is that for operators representing associative operations, we don't think of whether they associate to the left or right, but we may still care about how they're formatted), but it's certainly interesting to see how far we can push this heuristic.

**Comment by 314eter** [comment]
For associative operators both formatting styles can make sense. But strictly speaking, the formatter doesn't know that an operator is associative, since it can be redefined by the user. You could add some special cases for a few arithmetic operators, but do people have a strong preference on how they are formatted? I think it's more important that `+` has the same formatting as `+.`, `++`, and basically every other operator in the `add_operator` class.

Here is an overview of the different operator classes and their associativity: https://github.com/tree-sitter/tree-sitter-ocaml/blob/3ad4d7988edf8b8a9780a1db7a5af657911dbfba/ocaml/grammar.js#L1119-L1160

**Comment by 314eter** [comment]
> Wait; is there a way for a user to redefine the syntactic associativity of an operator in OCaml?

No, there is not. What I meant is that every operator in OCaml is either left or right associative (syntactically), but some arithmetic operators like `+` and `*` are associative in the mathematical sense, which I think is what @aspiwack's comment was about. But you can redefine `let ( + ) = ( |> )`, and then it's not mathematically associative anymore.

> I think? which would probably be considered “wrong” by many people.

I think the special case you could hardcode here is not an exception for the `>>=` operator, but an exception for any operator followed by a `fun` expression.
