### ISSUE TITLE
Make sure the release binaries have working queries out of the box

### ISSUE THREAD

**Issue by torhovland** [tweag/topiary#542]
**Is your feature request related to a problem? Please describe.**
We are now releasing binaries with `cargo-dist`. See #538. But we are not distributing any query files. This means that a downloaded package will not work out of the box.

**Describe the solution you'd like**
Either we have to find a way to include the query files with `cargo-dist`, or, probably preferably, the Topiary CLI can use the new convenience functions to access compile-time query files. See #528.

**Describe alternatives you've considered**
The user can always download query files manually.

**Comment by ErinvanderVeen** [comment]
I labelled this as P0 only because we need to have this before we create a new release. Fixing this should not result in a new patch release on its own.
