### ISSUE TITLE
Idempotency errors on the Nickel test suite

### ISSUE THREAD

**Issue by yannham** [tweag/topiary#547]
**Describe the bug**
Running Topiary on the Nickel source files from Nickel's test suite produces a bunch of idempotency errors. In particular on the following files:

- [pass/contracts/contracts.ncl](https://github.com/tweag/nickel/blob/99531e68ad5cf325afeda43948c84fe38fa26d5b/core/tests/integration/pass/contracts/contracts.ncl)
- [pass/merging/metavalues.ncl](https://github.com/tweag/nickel/blob/99531e68ad5cf325afeda43948c84fe38fa26d5b/core/tests/integration/pass/merging/metavalues.ncl)
- [pass/stdlib/string_conversions.ncl](https://github.com/tweag/nickel/blob/99531e68ad5cf325afeda43948c84fe38fa26d5b/core/tests/integration/pass/stdlib/string_conversions.ncl)
- [fail/contracts/poly_record_contract_bad_field.ncl](https://github.com/tweag/nickel/blob/99531e68ad5cf325afeda43948c84fe38fa26d5b/core/tests/integration/fail/contracts/poly_record_contract_bad_field.ncl)
- [fail/contracts/poly_record_contract_higher_order_fn.ncl](https://github.com/tweag/nickel/blob/99531e68ad5cf325afeda43948c84fe38fa26d5b/core/tests/integration/fail/contracts/poly_record_contract_higher_order_fn.ncl)

There is a plain parse error on [pass/strings/string_interpolation.ncl](https://github.com/tweag/nickel/blob/master/core/tests/integration/pass/strings/string_interpolation.ncl), but this is heavy on nested string interpolations, and the tree-sitter grammar might be the culprit here.

**To Reproduce**
Check out the Nickel repo, and then:

```console
$ cd core/tests/integration
$ for f in **/*.ncl; do echo "Checking $f..."; topiary -i -f "$f"; done 
...
errors
...
```

Some tests are not supposed to parse (in particular in `fail/parser`), so those are expected to fail.

**Expected behavior**
Beside tests that aren't parsable, I expect the idempotency check to succeed on the Nickel test suite.

**Environment**
 - Version of the code: b4b3aa9f6fb6f8d220bcae033514327a32557786

**Comment by ErinvanderVeen** [comment]
I took a look at the first one (`contracts.ncl`).

When parsing a `quoted_enum_tag`, `tree-sitter-nickel` defers to its scanner. The scanner produces a `quoted_enum_tag_start`, which is taken by Topiary and produced correctly. The parser then produces a `chunk_literal_single` containing only the contents of the following string. I.e. the last quote ending the string is completely dropped by `tree-sitter-nickel`.

Adding the `(quoted_enum_tag) @leaf` query to the Nickel query file seemed to resolve that issue (although we might want to do something more intelligent).

**Comment by ErinvanderVeen** [comment]
> Adding the `(quoted_enum_tag) @leaf` query to the Nickel query file seemed to resolve that issue (although we might want to do something more intelligent).

This also resolves `string_conversions.ncl`.

**Comment by torhovland** [comment]
@yannham You are right that for `string_interpolation.ncl` the input just doesn't parse according to the grammar, so that particular error is not a Topiary issue.

I'm taking a look at the other ones.

**Comment by torhovland** [comment]
For `metavalues.ncl`, this is a reproducible example:

```
[
  a &&
  (b & c | d)
]
```

**Comment by torhovland** [comment]
So the problem is that the first pass turns `(b & c | d)` from single-line to multi-line, which results in further formatting on the second pass.

I suppose we should not put a newline after that `b`.

**Comment by torhovland** [comment]
The problem seems to be that we need to introduce a scoped softline here. Because 

```
a &&
  (b & c | d)
```

is multiline, the current query wants to add softlines after all terms, and it doesn't see a difference between the `a` and the `b`.

**Comment by torhovland** [comment]
@nbacquey Actually, there is already scoped handling here, but there is something wrong with `@prepend_spaced_scoped_softline`.

We have this in the query:

```scheme
; Flow a chain of infix expressions over new lines, in a multi-line
; context. Note that we _don't_ want this to happen for comparison
; operators, which fall under nodes (infix_b_op_7) and (infix_b_op_8).
(uni_term
  (#scope_id! "infix_chain")
  (infix_expr) @begin_scope
) @end_scope

(infix_expr
  (#scope_id! "infix_chain")
  (infix_expr)
  .
  [
    (infix_b_op_2) ; ++ and @
    (infix_b_op_3) ; *, / and %
    (infix_b_op_4) ; + and -
    (infix_b_op_6) ; & and |>
    (infix_lazy_b_op_9) ; &&
    (infix_lazy_b_op_10) ; ||
  ] @prepend_spaced_scoped_softline
  .
  (infix_expr)
)
```

It turns this:

```
[
  a &&
  (b & c | d)
]
```

into this:

```
[
  a
  && (b
    & c | d)
]
```

The documentation says this:

> When one of these scoped softlines is used, their behaviour depends on
the innermost encompassing scope with the corresponding `scope_id`. If
that scope is multi-line, the softline expands into a line break. In any
other regard, they behave as their non-`scoped` counterparts.

So the parenthesized part should behave the same if I make the query non-`scoped`. But when I change `@prepend_spaced_scoped_softline` to `@prepend_spaced_softline` I get this:

```
[
  a
  && (b & c | d)
]
```

**Comment by torhovland** [comment]
I take it back, `@prepend_spaced_scoped_softline` is working as documented. The inner `infix_chain` scope here is

```
a &&
  (b & c | d)
```

which is multi-line. The parenthesized part is not matched, becase it is `uni_term -> annotated_infix_expr -> infix_expr` rather than just `uni_term -> infix_expr`.

**Comment by torhovland** [comment]
Next problem in the same file can be summarised as this:

```
(
  # Foo
)
```

It gets formatted as:

```
(

  # Foo

)
```

and then as:

```
(


  # Foo

)
```

**Comment by torhovland** [comment]
Looks like this at least partially depends on https://github.com/tweag/topiary/issues/549.

**Comment by ErinvanderVeen** [comment]
About the bug in the tree-sitter grammar. The string `m%%""%%{s}" World"%%` is parsed too greedily by our tree-sitter grammar. It considers the first part: `m%%""%%` to be the entire string, and then enters error recovery when it finds the unexpected `{`. To avoid this, the scanner should somehow attempt to parse interpolation first, before the end of the string.

**Comment by yannham** [comment]
Ok, looking at the string interpolation example again, I'm not sure the current behavior of the Nickel parser is the most reasonable at all :cold_sweat: . I think this tests dates back to those times where a trailing `m` was required for the closing delimiter, such as in `m%%" foo "%%m`.

In fact I'm pretty convinced `m%%""%%` should be interpreted as an empty string indeed, whatever is coming after. I'm lending toward the tree sitter grammar doing the right thing, and the Nickel parser having a bug

**Comment by ErinvanderVeen** [comment]
For the remaining two files:
```
id | a
  -> a
```
Is a minimal working example.

**Comment by yannham** [comment]
Cf https://github.com/tweag/nickel/issues/1429, tree-sitter correctly fails on [pass/strings/string_interpolation.ncl](https://github.com/tweag/nickel/blob/master/core/tests/integration/pass/strings/string_interpolation.ncl), as Nickel should as well. We can forget about this one :slightly_smiling_face:
