### ISSUE TITLE
Nickel formatting regression

### ISSUE THREAD

**Issue by vkleen** [tweag/topiary#571]
The following Nickel code used to be formatted correctly according to topiary:

```nickel
{
  kind = 'ReplicationController,
} | KubernetesConfig
```

At least current HEAD 817eb4dfeb82b47038181f9d94c5741add620d60 insists on putting a newline before the contract application `|`:

```nickel
{
  kind = 'ReplicationController,
}
  | KubernetesConfig
```

This should only happen if multiple contract annotations occur, in my opinion.

**Comment by ErinvanderVeen** [comment]
Thank you for the report. There is some internal discussion happening right now about how to solve this best.

This is a regression of https://github.com/tweag/topiary/pull/554
