### ISSUE TITLE
Scope prepend and append

### ISSUE THREAD

**Issue by ErinvanderVeen** [tweag/topiary#572]
Issue #571 is best fixed by appending `open_scope` to the expression before the annotation. We should implement these new directives:

- `prepend_open_scope`
- `append_open_scope`
- `prepend_close_scope`
- `append_close_scope`

**Comment by torhovland** [comment]
Perhaps we should change scopes to work like indenting, i.e. adding atoms for `ScopeStart` and `ScopeEnd`.
