### ISSUE TITLE
Redundant workspace dependencies

### ISSUE THREAD

**Issue by Xophmeister** [tweag/topiary#584]
In the root `Cargo.toml` there are a number of workspace-wide dependencies that are only used by one-or-two subprojects. For example, `cfg-if` is only used by the playground, `clap` is only used by the library and CLI.

Is there a technical need for this, or is it just accumulated cruft?

(I don't think this really matters -- I assume unused dependencies will be compiled away -- hence P4.)

**Comment by torhovland** [comment]
The reason for this is to collect all dependency version numbers in one place. So if another project decides to use `cfg-if`, it will refer to the version number in the root `Cargo.toml`.

**Comment by ErinvanderVeen** [comment]
It's not that they are removed during compilation as some kind of optimization, they are never even considered. When building, only the dependencies listed in the individual package's Cargo.toml are considered. If they happen to be workspace dependencies, that version is used. They do not automatically include all workspace dependencies.

**Comment by Xophmeister** [comment]
Makes sense... One further question: What about features? The reason I made this is issue is because I noticed the features for Clap in `topiary-cli` diverged from those in the root. Should the same rule apply: features should be specified in the root `Cargo.toml`, leaving the leaf `Cargo.toml` files to just inherit this? Or is this just for the sake of pinning versions?

**Comment by ErinvanderVeen** [comment]
That's only for versions. Indeed our different crates can require different features from a package, and so those should be defined (IMO) by the individual crates.
