### ISSUE TITLE
Topiary CLI fails when output file doesn't exist

### ISSUE THREAD

**Issue by vkleen** [tweag/topiary#588]
The topiary CLI complains about "File not found" when given an output file that doesn't exist yet, using the `-o` flag.

The root cause here is that `topiary` tries to call `path::canonicalize()` on the output file path. This call will fail for paths that don't point to existing files. In Nickel I intend to solve this issue [like this](https://github.com/tweag/nickel/blob/54fe83b6112f9b9c5516d0d5e195f5974d03a85a/cli/src/format.rs#L61). Basically, if the `canonicalize()` call fails with "File not found" I just hope for the best and continue with the original path as passed by the user.

**Comment by ErinvanderVeen** [comment]
I love it when a bug report comes with a proposed solution.

**Comment by Xophmeister** [comment]
Note: #583 -- when it's ready -- will supersede this problem, as `-o` will no longer be a thing.
