### ISSUE TITLE
New language from existing tree-sitter repo

### ISSUE THREAD

**Issue by sdankel** [tweag/topiary#595]
I have an existing tree-sitter repo, [tree-sitter-sway]( https://github.com/FuelLabs/tree-sitter-sway) and I'm interested in plugging it into topiary. However, it looks like topiary only reads from 1 .scm file per language, and my tree-sitter repo has it split out into 5 .scm files, plus some C files for additional parsing. 

I would like to be able to specify the tree-sitter repo rather than having to copy the queries into topiary, so that I only have to maintain the tree-sitter grammar in one place. Something like the way [helix editor](https://github.com/sdankel/helix/blob/555a4b34b7c304af55ec99849e884a811754ad5e/languages.toml#L65) does it would be excellent - specifying the tree-sitter repo in languages.toml.

**Comment by Xophmeister** [comment]
Thanks for bringing this up. There is a long-outstanding proposal for dynamic loading of Tree-sitter grammars (see #4); the obvious place to configure this would be in the configuration, as you say. However, your suggestion goes further still and suggests that the Topiary formatting query files could _also_ be read from the upstream repo.

This seems like an excellent idea to me, as it naturally pins the formatting queries to the grammar at the same commit. However, I'm not sure I quite understand your point about using multiple query files; the Topiary query files are tightly coupled to Topiary and wouldn't make sense elsewhere (and vice versa). Could you please explain how you'd expect it to work, or would standardising on, say, `queries/topiary.scm` in Tree-sitter grammar repos suffice?[^buy-in]

[^buy-in]: The upstream queries would take precedence, presumably, if they exist, but Topiary would still need to fallback to/have the option of using local query files if there's no upstream buy-in.

**Comment by sdankel** [comment]
After looking deeper into topiary I have a better understanding now. The topiary query scm file that defines the formatting is separate from the tree sitter grammar that define the language/AST.

I'm not sure that putting the topiary queries in tree-sitter would add much value at the moment since the commits in tree-sitter are already pinned (or can be pinned) to a version of the tree-sitter grammar (correct?). I could see it being useful if topiary became a common use-case for tree-sitter.

I think https://github.com/tweag/topiary/issues/4 is pretty much what I was asking for, so I'll close this issue as a duplicate. Thanks!
