### ISSUE TITLE
Completely remove all non formatting tasks from the topiary crate

### ISSUE THREAD

**Issue by ErinvanderVeen** [tweag/topiary#606]
We envision a future where Topiary can be used as a formatting engine in other projects (e.g. text editors, Nickel). Such use cases do not care much about out language detection and configuration parsing stuff. They will handle that on their own.

**What I would like to see**
- `topiary` should be a crate that just contains our wonderful formatting engine.
- `topiary-cli` should be a crate that handles all IO, including parsing the topiary configuration and language detection.
- `topiary-query-files` should be a crate that (behind the features flags) contains all the default query files as static string. Specifying the `nickel` and `ocaml` feature flags will export exactly those query files.

TODO:
- [x] Create `topiary-query-files` (#609)
- [ ] Move all configuration to `topiary-cli`

**Comment by Xophmeister** [comment]
Resolved in #672
