### ISSUE TITLE
Cargo install fails

### ISSUE THREAD

**Issue by ErinvanderVeen** [tweag/topiary#690]
**Describe the bug**
Cargo install doesn't build because `cargo install` ignores the lockfile and can then not select the right `tree-sitter` version.

**To Reproduce**
`cargo install`

**Expected behavior**
Installed topiary

**Environment**
 - OS name + version: NixOS 23.11
 - Version of the code: `main`

**Comment by Jasha10** [comment]
I had success passing `--locked` flag to the `cargo install` command.
```bash
cargo install --path topiary-cli --locked
```
