### ISSUE TITLE
Topiary errors if `~/.cache` does not exist

### ISSUE THREAD

**Issue by rrthomas** [tweag/topiary#740]
**Describe the bug**
Running topiary without `~/.cache` in existence errors when topiary tries to mkdir `~/.cache/topiary`.

**Environment**
 - OS name + version: Ubuntu 22.04 (in GitHub CI)
 - Version of the code: 0.4.2

**Additional context**
This took me a while to figure out, when I was trying to use topiary in GitHub CI!

**Comment by ErinvanderVeen** [comment]
Thank you for the report. I believe #741 resolves this issue.

**Comment by rrthomas** [comment]
Many thanks for the quick fix!
