### ISSUE TITLE
Merging configuration does not work as expected with defaults (using nixSupport)

### ISSUE THREAD

**Issue by toastal** [tweag/topiary#808]
```sh-session
$ cat .topiary.ncl
{
  languages = {
    bash.indent | priority 1 = "	" ,
    css.indent | priority 1 = "	" ,
    json.indent | priority 1 = "	" ,
    nickel.indent | priority 1 = "	",
    ocaml.indent | priority 1 = "	" ,
    ocaml_interface.indent | priority 1 = "	",
    ocamllex.indent | priority 1 = "	",
    rust.indent | priority 1 = "	" ,
    toml.indent | priority 1 = "	",
  },
}
$ topiary --merge-configuration --configuration .topiary.ncl config
[2024-12-11T09:10:36Z ERROR topiary] Nickel error: Other(
        "missing field `extensions`",
    )
```

I would have expected this to merge with Topiary’s default configuration instead of throwing an error. This _should_ match the docs, but does not work as the documentation states.

Environment:
* OS name + version: NixOS 25.05
* Version of the code: topiary-cli 0.5.1 (`main` branch flake)

---

Edit: this seems to be an issue with `topiary-cli-nix` only, but the documentation doesn’t clarify what these are.

[^1]

[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.

**Comment by Xophmeister** [comment]
I can't replicate this in `8be1a9a8a8c506`; it works as documented. Do you have the `TOPIARY_CONFIG_FILE` environment variable set and pointing to configuration which is missing the `extensions` field for any language (even then, it reverts back to the builtin config, for me)?
