### ISSUE TITLE
Configurable operator precedence

### ISSUE THREAD

**Issue by torhovland** [tweag/topiary#89]
See #87 for background.

Currently the formatter can output strictly single-line or strictly multi-line. Sometimes you want something in-between.

Rather than formatting this:

```ocaml
(?used_slot: bool ref ->
  override_flag ->
  Env.t ->
  Location.t ->
  Longident.t loc -> 
  Path.t *
  Env.t)
```

the user will probably prefer this:

```ocaml
(?used_slot: bool ref ->
  override_flag ->
  Env.t ->
  Location.t ->
  Longident.t loc -> 
  Path.t * Env.t)
```

We could define precedence in the config section of the query file, like this:

```scheme
(#precedence! * + ->)
```

And then, somehow use this during formatting.

**Comment by nbacquey** [comment]
As the snippet above is currently formatted with `Path.t * Env.t` on the same line, thanks to custom scopes, I think we can close this issue.
